SEASPRAY_TOWN_10_0_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_10_0/border.bin"

SEASPRAY_TOWN_10_0_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_10_0/map.bin"

	.align 2
SEASPRAY_TOWN_10_0_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x00000015  @Map Height
    .4byte    SEASPRAY_TOWN_10_0_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_10_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_10_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_10_0_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_10_1_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_10_1/border.bin"

SEASPRAY_TOWN_10_1_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_10_1/map.bin"

	.align 2
SEASPRAY_TOWN_10_1_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x00000015  @Map Height
    .4byte    SEASPRAY_TOWN_10_1_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_10_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_10_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_10_1_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_10_2_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_10_2/border.bin"

SEASPRAY_TOWN_10_2_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_10_2/map.bin"

	.align 2
SEASPRAY_TOWN_10_2_Layout::
    .4byte    0x00000057  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    SEASPRAY_TOWN_10_2_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_10_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_10_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_10_2_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_10_4_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_10_4/border.bin"

SEASPRAY_TOWN_10_4_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_10_4/map.bin"

	.align 2
SEASPRAY_TOWN_10_4_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    SEASPRAY_TOWN_10_4_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_10_4_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_10_4_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_10_4_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_10_5_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_10_5/border.bin"

SEASPRAY_TOWN_10_5_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_10_5/map.bin"

	.align 2
SEASPRAY_TOWN_10_5_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x0000000F  @Map Height
    .4byte    SEASPRAY_TOWN_10_5_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_10_5_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_10_5_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_10_5_SecondaryTileset  @Secondary Tileset
TRAINER_ISLE_10_3_MapBorder::
	.incbin "data/layouts/TRAINER_ISLE_10_3/border.bin"

TRAINER_ISLE_10_3_MapBlockdata::
	.incbin "data/layouts/TRAINER_ISLE_10_3/map.bin"

	.align 2
TRAINER_ISLE_10_3_Layout::
    .4byte    0x00000026  @Map Width
    .4byte    0x0000000D  @Map Height
    .4byte    TRAINER_ISLE_10_3_MapBorder  @Border Data
    .4byte    TRAINER_ISLE_10_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TRAINER_ISLE_10_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TRAINER_ISLE_10_3_SecondaryTileset  @Secondary Tileset
TRAINER_ISLE_10_3_MapBorder::
	.incbin "data/layouts/TRAINER_ISLE_10_3/border.bin"

TRAINER_ISLE_10_3_MapBlockdata::
	.incbin "data/layouts/TRAINER_ISLE_10_3/map.bin"

	.align 2
TRAINER_ISLE_10_3_Layout::
    .4byte    0x00000026  @Map Width
    .4byte    0x0000000D  @Map Height
    .4byte    TRAINER_ISLE_10_3_MapBorder  @Border Data
    .4byte    TRAINER_ISLE_10_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TRAINER_ISLE_10_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TRAINER_ISLE_10_3_SecondaryTileset  @Secondary Tileset
TRAINER_ISLE_10_3_MapBorder::
	.incbin "data/layouts/TRAINER_ISLE_10_3/border.bin"

TRAINER_ISLE_10_3_MapBlockdata::
	.incbin "data/layouts/TRAINER_ISLE_10_3/map.bin"

	.align 2
TRAINER_ISLE_10_3_Layout::
    .4byte    0x00000026  @Map Width
    .4byte    0x0000000D  @Map Height
    .4byte    TRAINER_ISLE_10_3_MapBorder  @Border Data
    .4byte    TRAINER_ISLE_10_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TRAINER_ISLE_10_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TRAINER_ISLE_10_3_SecondaryTileset  @Secondary Tileset
CIANWOOD_CITY_10_6_MapBorder::
	.incbin "data/layouts/CIANWOOD_CITY_10_6/border.bin"

CIANWOOD_CITY_10_6_MapBlockdata::
	.incbin "data/layouts/CIANWOOD_CITY_10_6/map.bin"

	.align 2
CIANWOOD_CITY_10_6_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    CIANWOOD_CITY_10_6_MapBorder  @Border Data
    .4byte    CIANWOOD_CITY_10_6_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CIANWOOD_CITY_10_6_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CIANWOOD_CITY_10_6_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_10_7_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_10_7/border.bin"

CAPE_AZURE_10_7_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_10_7/map.bin"

	.align 2
CAPE_AZURE_10_7_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    CAPE_AZURE_10_7_MapBorder  @Border Data
    .4byte    CAPE_AZURE_10_7_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_10_7_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_10_7_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_0_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_0/border.bin"

OCEANVIEW_CITY_11_0_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_0/map.bin"

	.align 2
OCEANVIEW_CITY_11_0_Layout::
    .4byte    0x00000013  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    OCEANVIEW_CITY_11_0_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_0_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_1_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_1/border.bin"

OCEANVIEW_CITY_11_1_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_1/map.bin"

	.align 2
OCEANVIEW_CITY_11_1_Layout::
    .4byte    0x00000019  @Map Width
    .4byte    0x0000000F  @Map Height
    .4byte    OCEANVIEW_CITY_11_1_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_1_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_2_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_2/border.bin"

OCEANVIEW_CITY_11_2_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_2/map.bin"

	.align 2
OCEANVIEW_CITY_11_2_Layout::
    .4byte    0x00000013  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    OCEANVIEW_CITY_11_2_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_2_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_3_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_3/border.bin"

OCEANVIEW_CITY_11_3_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_3/map.bin"

	.align 2
OCEANVIEW_CITY_11_3_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000014  @Map Height
    .4byte    OCEANVIEW_CITY_11_3_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_3_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_4_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_4/border.bin"

OCEANVIEW_CITY_11_4_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_4/map.bin"

	.align 2
OCEANVIEW_CITY_11_4_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x0000000B  @Map Height
    .4byte    OCEANVIEW_CITY_11_4_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_4_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_4_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_4_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_5_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_5/border.bin"

OCEANVIEW_CITY_11_5_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_5/map.bin"

	.align 2
OCEANVIEW_CITY_11_5_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x0000000F  @Map Height
    .4byte    OCEANVIEW_CITY_11_5_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_5_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_5_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_5_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_6_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_6/border.bin"

OCEANVIEW_CITY_11_6_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_6/map.bin"

	.align 2
OCEANVIEW_CITY_11_6_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    OCEANVIEW_CITY_11_6_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_6_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_6_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_6_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_7_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_7/border.bin"

OCEANVIEW_CITY_11_7_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_7/map.bin"

	.align 2
OCEANVIEW_CITY_11_7_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    OCEANVIEW_CITY_11_7_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_7_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_7_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_7_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_8_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_8/border.bin"

OCEANVIEW_CITY_11_8_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_8/map.bin"

	.align 2
OCEANVIEW_CITY_11_8_Layout::
    .4byte    0x0000002A  @Map Width
    .4byte    0x00000016  @Map Height
    .4byte    OCEANVIEW_CITY_11_8_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_8_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_8_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_8_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_11_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_11/border.bin"

OCEANVIEW_CITY_11_11_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_11/map.bin"

	.align 2
OCEANVIEW_CITY_11_11_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    OCEANVIEW_CITY_11_11_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_11_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_11_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_11_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_12_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_12/border.bin"

OCEANVIEW_CITY_11_12_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_12/map.bin"

	.align 2
OCEANVIEW_CITY_11_12_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    OCEANVIEW_CITY_11_12_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_12_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_12_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_12_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_11_16_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_11_16/border.bin"

OCEANVIEW_CITY_11_16_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_11_16/map.bin"

	.align 2
OCEANVIEW_CITY_11_16_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    OCEANVIEW_CITY_11_16_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_11_16_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_11_16_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_11_16_SecondaryTileset  @Secondary Tileset
SOHEAL'S_STRAIT_11_9_MapBorder::
	.incbin "data/layouts/SOHEAL'S_STRAIT_11_9/border.bin"

SOHEAL'S_STRAIT_11_9_MapBlockdata::
	.incbin "data/layouts/SOHEAL'S_STRAIT_11_9/map.bin"

	.align 2
SOHEAL'S_STRAIT_11_9_Layout::
    .4byte    0x00000015  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    SOHEAL'S_STRAIT_11_9_MapBorder  @Border Data
    .4byte    SOHEAL'S_STRAIT_11_9_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SOHEAL'S_STRAIT_11_9_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SOHEAL'S_STRAIT_11_9_SecondaryTileset  @Secondary Tileset
HAUNTED_ISLE_11_10_MapBorder::
	.incbin "data/layouts/HAUNTED_ISLE_11_10/border.bin"

HAUNTED_ISLE_11_10_MapBlockdata::
	.incbin "data/layouts/HAUNTED_ISLE_11_10/map.bin"

	.align 2
HAUNTED_ISLE_11_10_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x0000000F  @Map Height
    .4byte    HAUNTED_ISLE_11_10_MapBorder  @Border Data
    .4byte    HAUNTED_ISLE_11_10_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_HAUNTED_ISLE_11_10_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_HAUNTED_ISLE_11_10_SecondaryTileset  @Secondary Tileset
MYSTERY_ISLAND_11_13_MapBorder::
	.incbin "data/layouts/MYSTERY_ISLAND_11_13/border.bin"

MYSTERY_ISLAND_11_13_MapBlockdata::
	.incbin "data/layouts/MYSTERY_ISLAND_11_13/map.bin"

	.align 2
MYSTERY_ISLAND_11_13_Layout::
    .4byte    0x00000014  @Map Width
    .4byte    0x00000014  @Map Height
    .4byte    MYSTERY_ISLAND_11_13_MapBorder  @Border Data
    .4byte    MYSTERY_ISLAND_11_13_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_MYSTERY_ISLAND_11_13_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_MYSTERY_ISLAND_11_13_SecondaryTileset  @Secondary Tileset
TRAINER_ISLE_11_14_MapBorder::
	.incbin "data/layouts/TRAINER_ISLE_11_14/border.bin"

TRAINER_ISLE_11_14_MapBlockdata::
	.incbin "data/layouts/TRAINER_ISLE_11_14/map.bin"

	.align 2
TRAINER_ISLE_11_14_Layout::
    .4byte    0x00000014  @Map Width
    .4byte    0x000000A0  @Map Height
    .4byte    TRAINER_ISLE_11_14_MapBorder  @Border Data
    .4byte    TRAINER_ISLE_11_14_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TRAINER_ISLE_11_14_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TRAINER_ISLE_11_14_SecondaryTileset  @Secondary Tileset
TRAINER_ISLE_11_15_MapBorder::
	.incbin "data/layouts/TRAINER_ISLE_11_15/border.bin"

TRAINER_ISLE_11_15_MapBlockdata::
	.incbin "data/layouts/TRAINER_ISLE_11_15/map.bin"

	.align 2
TRAINER_ISLE_11_15_Layout::
    .4byte    0x0000001C  @Map Width
    .4byte    0x00000094  @Map Height
    .4byte    TRAINER_ISLE_11_15_MapBorder  @Border Data
    .4byte    TRAINER_ISLE_11_15_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TRAINER_ISLE_11_15_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TRAINER_ISLE_11_15_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_0_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_0/border.bin"

SERENITY_ISLE_12_0_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_0/map.bin"

	.align 2
SERENITY_ISLE_12_0_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    SERENITY_ISLE_12_0_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_0_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_1_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_1/border.bin"

SERENITY_ISLE_12_1_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_1/map.bin"

	.align 2
SERENITY_ISLE_12_1_Layout::
    .4byte    0x00000030  @Map Width
    .4byte    0x00000024  @Map Height
    .4byte    SERENITY_ISLE_12_1_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_1_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_2_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_2/border.bin"

SERENITY_ISLE_12_2_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_2/map.bin"

	.align 2
SERENITY_ISLE_12_2_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x0000000F  @Map Height
    .4byte    SERENITY_ISLE_12_2_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_2_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_3_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_3/border.bin"

SERENITY_ISLE_12_3_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_3/map.bin"

	.align 2
SERENITY_ISLE_12_3_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    SERENITY_ISLE_12_3_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_3_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_4_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_4/border.bin"

SERENITY_ISLE_12_4_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_4/map.bin"

	.align 2
SERENITY_ISLE_12_4_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    SERENITY_ISLE_12_4_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_4_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_4_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_4_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_5_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_5/border.bin"

SERENITY_ISLE_12_5_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_5/map.bin"

	.align 2
SERENITY_ISLE_12_5_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    SERENITY_ISLE_12_5_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_5_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_5_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_5_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_6_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_6/border.bin"

SERENITY_ISLE_12_6_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_6/map.bin"

	.align 2
SERENITY_ISLE_12_6_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    SERENITY_ISLE_12_6_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_6_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_6_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_6_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_7_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_7/border.bin"

SERENITY_ISLE_12_7_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_7/map.bin"

	.align 2
SERENITY_ISLE_12_7_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    SERENITY_ISLE_12_7_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_7_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_7_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_7_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_8_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_8/border.bin"

SERENITY_ISLE_12_8_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_8/map.bin"

	.align 2
SERENITY_ISLE_12_8_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    SERENITY_ISLE_12_8_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_8_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_8_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_8_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_12_9_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_12_9/border.bin"

SERENITY_ISLE_12_9_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_12_9/map.bin"

	.align 2
SERENITY_ISLE_12_9_Layout::
    .4byte    0x00000030  @Map Width
    .4byte    0x00000024  @Map Height
    .4byte    SERENITY_ISLE_12_9_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_12_9_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_12_9_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_12_9_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_0_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_0/border.bin"

CAPE_AZURE_13_0_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_0/map.bin"

	.align 2
CAPE_AZURE_13_0_Layout::
    .4byte    0x0000002E  @Map Width
    .4byte    0x00000018  @Map Height
    .4byte    CAPE_AZURE_13_0_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_0_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_4_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_4/border.bin"

CAPE_AZURE_13_4_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_4/map.bin"

	.align 2
CAPE_AZURE_13_4_Layout::
    .4byte    0x0000001F  @Map Width
    .4byte    0x0000000C  @Map Height
    .4byte    CAPE_AZURE_13_4_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_4_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_4_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_4_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_5_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_5/border.bin"

CAPE_AZURE_13_5_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_5/map.bin"

	.align 2
CAPE_AZURE_13_5_Layout::
    .4byte    0x00000032  @Map Width
    .4byte    0x00000021  @Map Height
    .4byte    CAPE_AZURE_13_5_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_5_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_5_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_5_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_6_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_6/border.bin"

CAPE_AZURE_13_6_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_6/map.bin"

	.align 2
CAPE_AZURE_13_6_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x0000000F  @Map Height
    .4byte    CAPE_AZURE_13_6_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_6_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_6_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_6_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_7_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_7/border.bin"

CAPE_AZURE_13_7_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_7/map.bin"

	.align 2
CAPE_AZURE_13_7_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    CAPE_AZURE_13_7_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_7_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_7_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_7_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_8_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_8/border.bin"

CAPE_AZURE_13_8_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_8/map.bin"

	.align 2
CAPE_AZURE_13_8_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    CAPE_AZURE_13_8_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_8_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_8_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_8_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_10_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_10/border.bin"

CAPE_AZURE_13_10_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_10/map.bin"

	.align 2
CAPE_AZURE_13_10_Layout::
    .4byte    0x00000032  @Map Width
    .4byte    0x00000014  @Map Height
    .4byte    CAPE_AZURE_13_10_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_10_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_10_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_10_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_11_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_11/border.bin"

CAPE_AZURE_13_11_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_11/map.bin"

	.align 2
CAPE_AZURE_13_11_Layout::
    .4byte    0x00000057  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    CAPE_AZURE_13_11_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_11_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_11_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_11_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_12_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_12/border.bin"

CAPE_AZURE_13_12_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_12/map.bin"

	.align 2
CAPE_AZURE_13_12_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    CAPE_AZURE_13_12_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_12_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_12_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_12_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_13_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_13/border.bin"

CAPE_AZURE_13_13_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_13/map.bin"

	.align 2
CAPE_AZURE_13_13_Layout::
    .4byte    0x00000008  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    CAPE_AZURE_13_13_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_13_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_13_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_13_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_14_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_14/border.bin"

CAPE_AZURE_13_14_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_14/map.bin"

	.align 2
CAPE_AZURE_13_14_Layout::
    .4byte    0x00000057  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    CAPE_AZURE_13_14_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_14_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_14_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_14_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_13_15_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_13_15/border.bin"

CAPE_AZURE_13_15_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_13_15/map.bin"

	.align 2
CAPE_AZURE_13_15_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    CAPE_AZURE_13_15_MapBorder  @Border Data
    .4byte    CAPE_AZURE_13_15_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_13_15_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_13_15_SecondaryTileset  @Secondary Tileset
DREAMSPACE_13_1_MapBorder::
	.incbin "data/layouts/DREAMSPACE_13_1/border.bin"

DREAMSPACE_13_1_MapBlockdata::
	.incbin "data/layouts/DREAMSPACE_13_1/map.bin"

	.align 2
DREAMSPACE_13_1_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000015  @Map Height
    .4byte    DREAMSPACE_13_1_MapBorder  @Border Data
    .4byte    DREAMSPACE_13_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DREAMSPACE_13_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DREAMSPACE_13_1_SecondaryTileset  @Secondary Tileset
DREAMSPACE_13_2_MapBorder::
	.incbin "data/layouts/DREAMSPACE_13_2/border.bin"

DREAMSPACE_13_2_MapBlockdata::
	.incbin "data/layouts/DREAMSPACE_13_2/map.bin"

	.align 2
DREAMSPACE_13_2_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000015  @Map Height
    .4byte    DREAMSPACE_13_2_MapBorder  @Border Data
    .4byte    DREAMSPACE_13_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DREAMSPACE_13_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DREAMSPACE_13_2_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_13_3_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_13_3/border.bin"

PALMTREE_RESORT_13_3_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_13_3/map.bin"

	.align 2
PALMTREE_RESORT_13_3_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    PALMTREE_RESORT_13_3_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_13_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_13_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_13_3_SecondaryTileset  @Secondary Tileset
REIGN_ISLE_13_9_MapBorder::
	.incbin "data/layouts/REIGN_ISLE_13_9/border.bin"

REIGN_ISLE_13_9_MapBlockdata::
	.incbin "data/layouts/REIGN_ISLE_13_9/map.bin"

	.align 2
REIGN_ISLE_13_9_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000000E  @Map Height
    .4byte    REIGN_ISLE_13_9_MapBorder  @Border Data
    .4byte    REIGN_ISLE_13_9_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_REIGN_ISLE_13_9_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_REIGN_ISLE_13_9_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_13_16_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_13_16/border.bin"

SEASPRAY_TOWN_13_16_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_13_16/map.bin"

	.align 2
SEASPRAY_TOWN_13_16_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    SEASPRAY_TOWN_13_16_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_13_16_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_13_16_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_13_16_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_13_17_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_13_17/border.bin"

SEASPRAY_TOWN_13_17_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_13_17/map.bin"

	.align 2
SEASPRAY_TOWN_13_17_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    SEASPRAY_TOWN_13_17_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_13_17_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_13_17_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_13_17_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_13_18_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_13_18/border.bin"

SEASPRAY_TOWN_13_18_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_13_18/map.bin"

	.align 2
SEASPRAY_TOWN_13_18_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    SEASPRAY_TOWN_13_18_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_13_18_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_13_18_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_13_18_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_13_19_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_13_19/border.bin"

SEASPRAY_TOWN_13_19_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_13_19/map.bin"

	.align 2
SEASPRAY_TOWN_13_19_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    SEASPRAY_TOWN_13_19_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_13_19_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_13_19_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_13_19_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_13_20_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_13_20/border.bin"

SEASPRAY_TOWN_13_20_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_13_20/map.bin"

	.align 2
SEASPRAY_TOWN_13_20_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    SEASPRAY_TOWN_13_20_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_13_20_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_13_20_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_13_20_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_13_21_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_13_21/border.bin"

SEASPRAY_TOWN_13_21_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_13_21/map.bin"

	.align 2
SEASPRAY_TOWN_13_21_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x0000000C  @Map Height
    .4byte    SEASPRAY_TOWN_13_21_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_13_21_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_13_21_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_13_21_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_13_22_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_13_22/border.bin"

SEASPRAY_TOWN_13_22_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_13_22/map.bin"

	.align 2
SEASPRAY_TOWN_13_22_Layout::
    .4byte    0x00000005  @Map Width
    .4byte    0x00000006  @Map Height
    .4byte    SEASPRAY_TOWN_13_22_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_13_22_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_13_22_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_13_22_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_14_0_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_14_0/border.bin"

PALMTREE_RESORT_14_0_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_14_0/map.bin"

	.align 2
PALMTREE_RESORT_14_0_Layout::
    .4byte    0x0000001C  @Map Width
    .4byte    0x0000001E  @Map Height
    .4byte    PALMTREE_RESORT_14_0_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_14_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_14_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_14_0_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_14_1_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_14_1/border.bin"

PALMTREE_RESORT_14_1_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_14_1/map.bin"

	.align 2
PALMTREE_RESORT_14_1_Layout::
    .4byte    0x00000057  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    PALMTREE_RESORT_14_1_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_14_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_14_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_14_1_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_14_2_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_14_2/border.bin"

PALMTREE_RESORT_14_2_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_14_2/map.bin"

	.align 2
PALMTREE_RESORT_14_2_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    PALMTREE_RESORT_14_2_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_14_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_14_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_14_2_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_14_3_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_14_3/border.bin"

PALMTREE_RESORT_14_3_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_14_3/map.bin"

	.align 2
PALMTREE_RESORT_14_3_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x0000000F  @Map Height
    .4byte    PALMTREE_RESORT_14_3_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_14_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_14_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_14_3_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_14_4_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_14_4/border.bin"

PALMTREE_RESORT_14_4_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_14_4/map.bin"

	.align 2
PALMTREE_RESORT_14_4_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    PALMTREE_RESORT_14_4_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_14_4_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_14_4_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_14_4_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_14_5_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_14_5/border.bin"

PALMTREE_RESORT_14_5_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_14_5/map.bin"

	.align 2
PALMTREE_RESORT_14_5_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    PALMTREE_RESORT_14_5_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_14_5_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_14_5_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_14_5_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_14_6_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_14_6/border.bin"

PALMTREE_RESORT_14_6_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_14_6/map.bin"

	.align 2
PALMTREE_RESORT_14_6_Layout::
    .4byte    0x00000057  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    PALMTREE_RESORT_14_6_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_14_6_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_14_6_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_14_6_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_14_8_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_14_8/border.bin"

PALMTREE_RESORT_14_8_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_14_8/map.bin"

	.align 2
PALMTREE_RESORT_14_8_Layout::
    .4byte    0x00000015  @Map Width
    .4byte    0x0000000C  @Map Height
    .4byte    PALMTREE_RESORT_14_8_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_14_8_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_14_8_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_14_8_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_14_11_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_14_11/border.bin"

PALMTREE_RESORT_14_11_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_14_11/map.bin"

	.align 2
PALMTREE_RESORT_14_11_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    PALMTREE_RESORT_14_11_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_14_11_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_14_11_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_14_11_SecondaryTileset  @Secondary Tileset
FUSION_CO_14_7_MapBorder::
	.incbin "data/layouts/FUSION_CO_14_7/border.bin"

FUSION_CO_14_7_MapBlockdata::
	.incbin "data/layouts/FUSION_CO_14_7/map.bin"

	.align 2
FUSION_CO_14_7_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    FUSION_CO_14_7_MapBorder  @Border Data
    .4byte    FUSION_CO_14_7_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_FUSION_CO_14_7_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_FUSION_CO_14_7_SecondaryTileset  @Secondary Tileset
FUSION_CO_14_9_MapBorder::
	.incbin "data/layouts/FUSION_CO_14_9/border.bin"

FUSION_CO_14_9_MapBlockdata::
	.incbin "data/layouts/FUSION_CO_14_9/map.bin"

	.align 2
FUSION_CO_14_9_Layout::
    .4byte    0x0000001A  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    FUSION_CO_14_9_MapBorder  @Border Data
    .4byte    FUSION_CO_14_9_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_FUSION_CO_14_9_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_FUSION_CO_14_9_SecondaryTileset  @Secondary Tileset
FUSION_CO_14_10_MapBorder::
	.incbin "data/layouts/FUSION_CO_14_10/border.bin"

FUSION_CO_14_10_MapBlockdata::
	.incbin "data/layouts/FUSION_CO_14_10/map.bin"

	.align 2
FUSION_CO_14_10_Layout::
    .4byte    0x00000019  @Map Width
    .4byte    0x00000007  @Map Height
    .4byte    FUSION_CO_14_10_MapBorder  @Border Data
    .4byte    FUSION_CO_14_10_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_FUSION_CO_14_10_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_FUSION_CO_14_10_SecondaryTileset  @Secondary Tileset
GOLDENROD_CITY_14_12_MapBorder::
	.incbin "data/layouts/GOLDENROD_CITY_14_12/border.bin"

GOLDENROD_CITY_14_12_MapBlockdata::
	.incbin "data/layouts/GOLDENROD_CITY_14_12/map.bin"

	.align 2
GOLDENROD_CITY_14_12_Layout::
    .4byte    0x00000011  @Map Width
    .4byte    0x0000000B  @Map Height
    .4byte    GOLDENROD_CITY_14_12_MapBorder  @Border Data
    .4byte    GOLDENROD_CITY_14_12_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_GOLDENROD_CITY_14_12_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_GOLDENROD_CITY_14_12_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_0_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_0/border.bin"

DARKWOOD_TOWN_15_0_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_0/map.bin"

	.align 2
DARKWOOD_TOWN_15_0_Layout::
    .4byte    0x00000013  @Map Width
    .4byte    0x0000001A  @Map Height
    .4byte    DARKWOOD_TOWN_15_0_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_0_SecondaryTileset  @Secondary Tileset
PATH_OF_VICTORY_15_1_MapBorder::
	.incbin "data/layouts/PATH_OF_VICTORY_15_1/border.bin"

PATH_OF_VICTORY_15_1_MapBlockdata::
	.incbin "data/layouts/PATH_OF_VICTORY_15_1/map.bin"

	.align 2
PATH_OF_VICTORY_15_1_Layout::
    .4byte    0x00000010  @Map Width
    .4byte    0x0000001A  @Map Height
    .4byte    PATH_OF_VICTORY_15_1_MapBorder  @Border Data
    .4byte    PATH_OF_VICTORY_15_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PATH_OF_VICTORY_15_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PATH_OF_VICTORY_15_1_SecondaryTileset  @Secondary Tileset
PATH_OF_VICTORY_15_12_MapBorder::
	.incbin "data/layouts/PATH_OF_VICTORY_15_12/border.bin"

PATH_OF_VICTORY_15_12_MapBlockdata::
	.incbin "data/layouts/PATH_OF_VICTORY_15_12/map.bin"

	.align 2
PATH_OF_VICTORY_15_12_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    PATH_OF_VICTORY_15_12_MapBorder  @Border Data
    .4byte    PATH_OF_VICTORY_15_12_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PATH_OF_VICTORY_15_12_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PATH_OF_VICTORY_15_12_SecondaryTileset  @Secondary Tileset
TRAINER_ISLE_15_11_MapBorder::
	.incbin "data/layouts/TRAINER_ISLE_15_11/border.bin"

TRAINER_ISLE_15_11_MapBlockdata::
	.incbin "data/layouts/TRAINER_ISLE_15_11/map.bin"

	.align 2
TRAINER_ISLE_15_11_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    TRAINER_ISLE_15_11_MapBorder  @Border Data
    .4byte    TRAINER_ISLE_15_11_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TRAINER_ISLE_15_11_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TRAINER_ISLE_15_11_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_0_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_0/border.bin"

DARKWOOD_TOWN_15_0_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_0/map.bin"

	.align 2
DARKWOOD_TOWN_15_0_Layout::
    .4byte    0x00000013  @Map Width
    .4byte    0x0000001A  @Map Height
    .4byte    DARKWOOD_TOWN_15_0_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_0_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_2_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_2/border.bin"

DARKWOOD_TOWN_15_2_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_2/map.bin"

	.align 2
DARKWOOD_TOWN_15_2_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x0000000F  @Map Height
    .4byte    DARKWOOD_TOWN_15_2_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_2_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_3_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_3/border.bin"

DARKWOOD_TOWN_15_3_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_3/map.bin"

	.align 2
DARKWOOD_TOWN_15_3_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    DARKWOOD_TOWN_15_3_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_3_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_4_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_4/border.bin"

DARKWOOD_TOWN_15_4_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_4/map.bin"

	.align 2
DARKWOOD_TOWN_15_4_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    DARKWOOD_TOWN_15_4_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_4_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_4_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_4_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_5_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_5/border.bin"

DARKWOOD_TOWN_15_5_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_5/map.bin"

	.align 2
DARKWOOD_TOWN_15_5_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    DARKWOOD_TOWN_15_5_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_5_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_5_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_5_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_6_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_6/border.bin"

DARKWOOD_TOWN_15_6_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_6/map.bin"

	.align 2
DARKWOOD_TOWN_15_6_Layout::
    .4byte    0x0000001E  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    DARKWOOD_TOWN_15_6_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_6_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_6_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_6_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_7_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_7/border.bin"

DARKWOOD_TOWN_15_7_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_7/map.bin"

	.align 2
DARKWOOD_TOWN_15_7_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    DARKWOOD_TOWN_15_7_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_7_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_7_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_7_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_8_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_8/border.bin"

DARKWOOD_TOWN_15_8_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_8/map.bin"

	.align 2
DARKWOOD_TOWN_15_8_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x0000000A  @Map Height
    .4byte    DARKWOOD_TOWN_15_8_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_8_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_8_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_8_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_9_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_9/border.bin"

DARKWOOD_TOWN_15_9_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_9/map.bin"

	.align 2
DARKWOOD_TOWN_15_9_Layout::
    .4byte    0x0000001E  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    DARKWOOD_TOWN_15_9_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_9_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_9_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_9_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_10_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_10/border.bin"

DARKWOOD_TOWN_15_10_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_10/map.bin"

	.align 2
DARKWOOD_TOWN_15_10_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    DARKWOOD_TOWN_15_10_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_10_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_10_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_10_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_13_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_13/border.bin"

DARKWOOD_TOWN_15_13_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_13/map.bin"

	.align 2
DARKWOOD_TOWN_15_13_Layout::
    .4byte    0x00000024  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    DARKWOOD_TOWN_15_13_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_13_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_13_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_13_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_15_14_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_15_14/border.bin"

DARKWOOD_TOWN_15_14_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_15_14/map.bin"

	.align 2
DARKWOOD_TOWN_15_14_Layout::
    .4byte    0x00000013  @Map Width
    .4byte    0x00000049  @Map Height
    .4byte    DARKWOOD_TOWN_15_14_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_15_14_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_15_14_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_15_14_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_0_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_0/border.bin"

TUNOD_LEAGUE_16_0_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_0/map.bin"

	.align 2
TUNOD_LEAGUE_16_0_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000000E  @Map Height
    .4byte    TUNOD_LEAGUE_16_0_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_0_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_1_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_1/border.bin"

TUNOD_LEAGUE_16_1_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_1/map.bin"

	.align 2
TUNOD_LEAGUE_16_1_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000000E  @Map Height
    .4byte    TUNOD_LEAGUE_16_1_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_1_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_2_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_2/border.bin"

TUNOD_LEAGUE_16_2_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_2/map.bin"

	.align 2
TUNOD_LEAGUE_16_2_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000000E  @Map Height
    .4byte    TUNOD_LEAGUE_16_2_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_2_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_3_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_3/border.bin"

TUNOD_LEAGUE_16_3_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_3/map.bin"

	.align 2
TUNOD_LEAGUE_16_3_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000000E  @Map Height
    .4byte    TUNOD_LEAGUE_16_3_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_3_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_4_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_4/border.bin"

TUNOD_LEAGUE_16_4_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_4/map.bin"

	.align 2
TUNOD_LEAGUE_16_4_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000018  @Map Height
    .4byte    TUNOD_LEAGUE_16_4_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_4_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_4_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_4_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_10_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_10/border.bin"

TUNOD_LEAGUE_16_10_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_10/map.bin"

	.align 2
TUNOD_LEAGUE_16_10_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x0000000D  @Map Height
    .4byte    TUNOD_LEAGUE_16_10_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_10_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_10_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_10_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_11_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_11/border.bin"

TUNOD_LEAGUE_16_11_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_11/map.bin"

	.align 2
TUNOD_LEAGUE_16_11_Layout::
    .4byte    0x0000000F  @Map Width
    .4byte    0x00000011  @Map Height
    .4byte    TUNOD_LEAGUE_16_11_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_11_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_11_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_11_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_12_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_12/border.bin"

TUNOD_LEAGUE_16_12_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_12/map.bin"

	.align 2
TUNOD_LEAGUE_16_12_Layout::
    .4byte    0x0000000E  @Map Width
    .4byte    0x0000000F  @Map Height
    .4byte    TUNOD_LEAGUE_16_12_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_12_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_12_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_12_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_13_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_13/border.bin"

TUNOD_LEAGUE_16_13_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_13/map.bin"

	.align 2
TUNOD_LEAGUE_16_13_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    TUNOD_LEAGUE_16_13_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_13_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_13_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_13_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_16_14_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_16_14/border.bin"

TUNOD_LEAGUE_16_14_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_16_14/map.bin"

	.align 2
TUNOD_LEAGUE_16_14_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    TUNOD_LEAGUE_16_14_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_16_14_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_16_14_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_16_14_SecondaryTileset  @Secondary Tileset
JOHTO_LEAGUE_16_5_MapBorder::
	.incbin "data/layouts/JOHTO_LEAGUE_16_5/border.bin"

JOHTO_LEAGUE_16_5_MapBlockdata::
	.incbin "data/layouts/JOHTO_LEAGUE_16_5/map.bin"

	.align 2
JOHTO_LEAGUE_16_5_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000004C  @Map Height
    .4byte    JOHTO_LEAGUE_16_5_MapBorder  @Border Data
    .4byte    JOHTO_LEAGUE_16_5_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_JOHTO_LEAGUE_16_5_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_JOHTO_LEAGUE_16_5_SecondaryTileset  @Secondary Tileset
JOHTO_LEAGUE_16_6_MapBorder::
	.incbin "data/layouts/JOHTO_LEAGUE_16_6/border.bin"

JOHTO_LEAGUE_16_6_MapBlockdata::
	.incbin "data/layouts/JOHTO_LEAGUE_16_6/map.bin"

	.align 2
JOHTO_LEAGUE_16_6_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000004C  @Map Height
    .4byte    JOHTO_LEAGUE_16_6_MapBorder  @Border Data
    .4byte    JOHTO_LEAGUE_16_6_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_JOHTO_LEAGUE_16_6_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_JOHTO_LEAGUE_16_6_SecondaryTileset  @Secondary Tileset
JOHTO_LEAGUE_16_7_MapBorder::
	.incbin "data/layouts/JOHTO_LEAGUE_16_7/border.bin"

JOHTO_LEAGUE_16_7_MapBlockdata::
	.incbin "data/layouts/JOHTO_LEAGUE_16_7/map.bin"

	.align 2
JOHTO_LEAGUE_16_7_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000004C  @Map Height
    .4byte    JOHTO_LEAGUE_16_7_MapBorder  @Border Data
    .4byte    JOHTO_LEAGUE_16_7_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_JOHTO_LEAGUE_16_7_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_JOHTO_LEAGUE_16_7_SecondaryTileset  @Secondary Tileset
JOHTO_LEAGUE_16_8_MapBorder::
	.incbin "data/layouts/JOHTO_LEAGUE_16_8/border.bin"

JOHTO_LEAGUE_16_8_MapBlockdata::
	.incbin "data/layouts/JOHTO_LEAGUE_16_8/map.bin"

	.align 2
JOHTO_LEAGUE_16_8_Layout::
    .4byte    0x0000000F  @Map Width
    .4byte    0x0000002F  @Map Height
    .4byte    JOHTO_LEAGUE_16_8_MapBorder  @Border Data
    .4byte    JOHTO_LEAGUE_16_8_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_JOHTO_LEAGUE_16_8_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_JOHTO_LEAGUE_16_8_SecondaryTileset  @Secondary Tileset
JOHTO_LEAGUE_16_9_MapBorder::
	.incbin "data/layouts/JOHTO_LEAGUE_16_9/border.bin"

JOHTO_LEAGUE_16_9_MapBlockdata::
	.incbin "data/layouts/JOHTO_LEAGUE_16_9/map.bin"

	.align 2
JOHTO_LEAGUE_16_9_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000004C  @Map Height
    .4byte    JOHTO_LEAGUE_16_9_MapBorder  @Border Data
    .4byte    JOHTO_LEAGUE_16_9_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_JOHTO_LEAGUE_16_9_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_JOHTO_LEAGUE_16_9_SecondaryTileset  @Secondary Tileset
GOLDENROD_CITY_17_0_MapBorder::
	.incbin "data/layouts/GOLDENROD_CITY_17_0/border.bin"

GOLDENROD_CITY_17_0_MapBlockdata::
	.incbin "data/layouts/GOLDENROD_CITY_17_0/map.bin"

	.align 2
GOLDENROD_CITY_17_0_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x00000060  @Map Height
    .4byte    GOLDENROD_CITY_17_0_MapBorder  @Border Data
    .4byte    GOLDENROD_CITY_17_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_GOLDENROD_CITY_17_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_GOLDENROD_CITY_17_0_SecondaryTileset  @Secondary Tileset
TURQUOISE_BAY_17_1_MapBorder::
	.incbin "data/layouts/TURQUOISE_BAY_17_1/border.bin"

TURQUOISE_BAY_17_1_MapBlockdata::
	.incbin "data/layouts/TURQUOISE_BAY_17_1/map.bin"

	.align 2
TURQUOISE_BAY_17_1_Layout::
    .4byte    0x0000000F  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    TURQUOISE_BAY_17_1_MapBorder  @Border Data
    .4byte    TURQUOISE_BAY_17_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TURQUOISE_BAY_17_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TURQUOISE_BAY_17_1_SecondaryTileset  @Secondary Tileset
OVERSEAS_BRIDGE_18_0_MapBorder::
	.incbin "data/layouts/OVERSEAS_BRIDGE_18_0/border.bin"

OVERSEAS_BRIDGE_18_0_MapBlockdata::
	.incbin "data/layouts/OVERSEAS_BRIDGE_18_0/map.bin"

	.align 2
OVERSEAS_BRIDGE_18_0_Layout::
    .4byte    0x00000057  @Map Width
    .4byte    0x00000008  @Map Height
    .4byte    OVERSEAS_BRIDGE_18_0_MapBorder  @Border Data
    .4byte    OVERSEAS_BRIDGE_18_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OVERSEAS_BRIDGE_18_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OVERSEAS_BRIDGE_18_0_SecondaryTileset  @Secondary Tileset
OVERSEAS_BRIDGE_18_1_MapBorder::
	.incbin "data/layouts/OVERSEAS_BRIDGE_18_1/border.bin"

OVERSEAS_BRIDGE_18_1_MapBlockdata::
	.incbin "data/layouts/OVERSEAS_BRIDGE_18_1/map.bin"

	.align 2
OVERSEAS_BRIDGE_18_1_Layout::
    .4byte    0x0000000C  @Map Width
    .4byte    0x0000000D  @Map Height
    .4byte    OVERSEAS_BRIDGE_18_1_MapBorder  @Border Data
    .4byte    OVERSEAS_BRIDGE_18_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OVERSEAS_BRIDGE_18_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OVERSEAS_BRIDGE_18_1_SecondaryTileset  @Secondary Tileset
NORTHCOAST_TOWN_19_0_MapBorder::
	.incbin "data/layouts/NORTHCOAST_TOWN_19_0/border.bin"

NORTHCOAST_TOWN_19_0_MapBlockdata::
	.incbin "data/layouts/NORTHCOAST_TOWN_19_0/map.bin"

	.align 2
NORTHCOAST_TOWN_19_0_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000000C  @Map Height
    .4byte    NORTHCOAST_TOWN_19_0_MapBorder  @Border Data
    .4byte    NORTHCOAST_TOWN_19_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_NORTHCOAST_TOWN_19_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_NORTHCOAST_TOWN_19_0_SecondaryTileset  @Secondary Tileset
ICICLE_TUNNEL_19_1_MapBorder::
	.incbin "data/layouts/ICICLE_TUNNEL_19_1/border.bin"

ICICLE_TUNNEL_19_1_MapBlockdata::
	.incbin "data/layouts/ICICLE_TUNNEL_19_1/map.bin"

	.align 2
ICICLE_TUNNEL_19_1_Layout::
    .4byte    0x0000000D  @Map Width
    .4byte    0x0000000C  @Map Height
    .4byte    ICICLE_TUNNEL_19_1_MapBorder  @Border Data
    .4byte    ICICLE_TUNNEL_19_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_ICICLE_TUNNEL_19_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_ICICLE_TUNNEL_19_1_SecondaryTileset  @Secondary Tileset
TRAINER_ISLE_20_0_MapBorder::
	.incbin "data/layouts/TRAINER_ISLE_20_0/border.bin"

TRAINER_ISLE_20_0_MapBlockdata::
	.incbin "data/layouts/TRAINER_ISLE_20_0/map.bin"

	.align 2
TRAINER_ISLE_20_0_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x0000000E  @Map Height
    .4byte    TRAINER_ISLE_20_0_MapBorder  @Border Data
    .4byte    TRAINER_ISLE_20_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TRAINER_ISLE_20_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TRAINER_ISLE_20_0_SecondaryTileset  @Secondary Tileset
NORTHCOAST_PEAK_20_1_MapBorder::
	.incbin "data/layouts/NORTHCOAST_PEAK_20_1/border.bin"

NORTHCOAST_PEAK_20_1_MapBlockdata::
	.incbin "data/layouts/NORTHCOAST_PEAK_20_1/map.bin"

	.align 2
NORTHCOAST_PEAK_20_1_Layout::
    .4byte    0x00000030  @Map Width
    .4byte    0x0000001E  @Map Height
    .4byte    NORTHCOAST_PEAK_20_1_MapBorder  @Border Data
    .4byte    NORTHCOAST_PEAK_20_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_NORTHCOAST_PEAK_20_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_NORTHCOAST_PEAK_20_1_SecondaryTileset  @Secondary Tileset
TRAINER_ISLE_20_2_MapBorder::
	.incbin "data/layouts/TRAINER_ISLE_20_2/border.bin"

TRAINER_ISLE_20_2_MapBlockdata::
	.incbin "data/layouts/TRAINER_ISLE_20_2/map.bin"

	.align 2
TRAINER_ISLE_20_2_Layout::
    .4byte    0x00000012  @Map Width
    .4byte    0x0000000E  @Map Height
    .4byte    TRAINER_ISLE_20_2_MapBorder  @Border Data
    .4byte    TRAINER_ISLE_20_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TRAINER_ISLE_20_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TRAINER_ISLE_20_2_SecondaryTileset  @Secondary Tileset
NITCHSIDE_COVE_21_0_MapBorder::
	.incbin "data/layouts/NITCHSIDE_COVE_21_0/border.bin"

NITCHSIDE_COVE_21_0_MapBlockdata::
	.incbin "data/layouts/NITCHSIDE_COVE_21_0/map.bin"

	.align 2
NITCHSIDE_COVE_21_0_Layout::
    .4byte    0x0000000A  @Map Width
    .4byte    0x00000009  @Map Height
    .4byte    NITCHSIDE_COVE_21_0_MapBorder  @Border Data
    .4byte    NITCHSIDE_COVE_21_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_NITCHSIDE_COVE_21_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_NITCHSIDE_COVE_21_0_SecondaryTileset  @Secondary Tileset
TND._SAFARI_ZONE_23_0_MapBorder::
	.incbin "data/layouts/TND._SAFARI_ZONE_23_0/border.bin"

TND._SAFARI_ZONE_23_0_MapBlockdata::
	.incbin "data/layouts/TND._SAFARI_ZONE_23_0/map.bin"

	.align 2
TND._SAFARI_ZONE_23_0_Layout::
    .4byte    0x00000024  @Map Width
    .4byte    0x0000000E  @Map Height
    .4byte    TND._SAFARI_ZONE_23_0_MapBorder  @Border Data
    .4byte    TND._SAFARI_ZONE_23_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TND._SAFARI_ZONE_23_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TND._SAFARI_ZONE_23_0_SecondaryTileset  @Secondary Tileset
HAUNTED_ROCK_24_0_MapBorder::
	.incbin "data/layouts/HAUNTED_ROCK_24_0/border.bin"

HAUNTED_ROCK_24_0_MapBlockdata::
	.incbin "data/layouts/HAUNTED_ROCK_24_0/map.bin"

	.align 2
HAUNTED_ROCK_24_0_Layout::
    .4byte    0x0000001E  @Map Width
    .4byte    0x0000002A  @Map Height
    .4byte    HAUNTED_ROCK_24_0_MapBorder  @Border Data
    .4byte    HAUNTED_ROCK_24_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_HAUNTED_ROCK_24_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_HAUNTED_ROCK_24_0_SecondaryTileset  @Secondary Tileset
HAUNTED_ROCK_24_1_MapBorder::
	.incbin "data/layouts/HAUNTED_ROCK_24_1/border.bin"

HAUNTED_ROCK_24_1_MapBlockdata::
	.incbin "data/layouts/HAUNTED_ROCK_24_1/map.bin"

	.align 2
HAUNTED_ROCK_24_1_Layout::
    .4byte    0x0000000B  @Map Width
    .4byte    0x0000000B  @Map Height
    .4byte    HAUNTED_ROCK_24_1_MapBorder  @Border Data
    .4byte    HAUNTED_ROCK_24_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_HAUNTED_ROCK_24_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_HAUNTED_ROCK_24_1_SecondaryTileset  @Secondary Tileset
HAUNTED_ROCK_24_2_MapBorder::
	.incbin "data/layouts/HAUNTED_ROCK_24_2/border.bin"

HAUNTED_ROCK_24_2_MapBlockdata::
	.incbin "data/layouts/HAUNTED_ROCK_24_2/map.bin"

	.align 2
HAUNTED_ROCK_24_2_Layout::
    .4byte    0x0000001D  @Map Width
    .4byte    0x00000026  @Map Height
    .4byte    HAUNTED_ROCK_24_2_MapBorder  @Border Data
    .4byte    HAUNTED_ROCK_24_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_HAUNTED_ROCK_24_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_HAUNTED_ROCK_24_2_SecondaryTileset  @Secondary Tileset
HAUNTED_ROCK_24_3_MapBorder::
	.incbin "data/layouts/HAUNTED_ROCK_24_3/border.bin"

HAUNTED_ROCK_24_3_MapBlockdata::
	.incbin "data/layouts/HAUNTED_ROCK_24_3/map.bin"

	.align 2
HAUNTED_ROCK_24_3_Layout::
    .4byte    0x0000001E  @Map Width
    .4byte    0x0000001E  @Map Height
    .4byte    HAUNTED_ROCK_24_3_MapBorder  @Border Data
    .4byte    HAUNTED_ROCK_24_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_HAUNTED_ROCK_24_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_HAUNTED_ROCK_24_3_SecondaryTileset  @Secondary Tileset
HAUNTED_ROCK_24_107_MapBorder::
	.incbin "data/layouts/HAUNTED_ROCK_24_107/border.bin"

HAUNTED_ROCK_24_107_MapBlockdata::
	.incbin "data/layouts/HAUNTED_ROCK_24_107/map.bin"

	.align 2
HAUNTED_ROCK_24_107_Layout::
    .4byte    0x00000011  @Map Width
    .4byte    0x00000019  @Map Height
    .4byte    HAUNTED_ROCK_24_107_MapBorder  @Border Data
    .4byte    HAUNTED_ROCK_24_107_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_HAUNTED_ROCK_24_107_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_HAUNTED_ROCK_24_107_SecondaryTileset  @Secondary Tileset
GREEN_SWAMP_24_4_MapBorder::
	.incbin "data/layouts/GREEN_SWAMP_24_4/border.bin"

GREEN_SWAMP_24_4_MapBlockdata::
	.incbin "data/layouts/GREEN_SWAMP_24_4/map.bin"

	.align 2
GREEN_SWAMP_24_4_Layout::
    .4byte    0x00000024  @Map Width
    .4byte    0x00000018  @Map Height
    .4byte    GREEN_SWAMP_24_4_MapBorder  @Border Data
    .4byte    GREEN_SWAMP_24_4_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_GREEN_SWAMP_24_4_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_GREEN_SWAMP_24_4_SecondaryTileset  @Secondary Tileset
