NORTHCOAST_TOWN_0_0_MapBorder::
	.incbin "data/layouts/NORTHCOAST_TOWN_0_0/border.bin"

NORTHCOAST_TOWN_0_0_MapBlockdata::
	.incbin "data/layouts/NORTHCOAST_TOWN_0_0/map.bin"

	.align 2
NORTHCOAST_TOWN_0_0_Layout::
    .4byte    0x00000028  @Map Width
    .4byte    0x00000028  @Map Height
    .4byte    NORTHCOAST_TOWN_0_0_MapBorder  @Border Data
    .4byte    NORTHCOAST_TOWN_0_0_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_NORTHCOAST_TOWN_0_0_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_NORTHCOAST_TOWN_0_0_SecondaryTileset  @Secondary Tileset
SOUTHERLY_CITY_0_1_MapBorder::
	.incbin "data/layouts/SOUTHERLY_CITY_0_1/border.bin"

SOUTHERLY_CITY_0_1_MapBlockdata::
	.incbin "data/layouts/SOUTHERLY_CITY_0_1/map.bin"

	.align 2
SOUTHERLY_CITY_0_1_Layout::
    .4byte    0x00000028  @Map Width
    .4byte    0x0000003C  @Map Height
    .4byte    SOUTHERLY_CITY_0_1_MapBorder  @Border Data
    .4byte    SOUTHERLY_CITY_0_1_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SOUTHERLY_CITY_0_1_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SOUTHERLY_CITY_0_1_SecondaryTileset  @Secondary Tileset
SEASPRAY_TOWN_0_2_MapBorder::
	.incbin "data/layouts/SEASPRAY_TOWN_0_2/border.bin"

SEASPRAY_TOWN_0_2_MapBlockdata::
	.incbin "data/layouts/SEASPRAY_TOWN_0_2/map.bin"

	.align 2
SEASPRAY_TOWN_0_2_Layout::
    .4byte    0x0000002A  @Map Width
    .4byte    0x00000028  @Map Height
    .4byte    SEASPRAY_TOWN_0_2_MapBorder  @Border Data
    .4byte    SEASPRAY_TOWN_0_2_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SEASPRAY_TOWN_0_2_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SEASPRAY_TOWN_0_2_SecondaryTileset  @Secondary Tileset
OCEANVIEW_CITY_0_3_MapBorder::
	.incbin "data/layouts/OCEANVIEW_CITY_0_3/border.bin"

OCEANVIEW_CITY_0_3_MapBlockdata::
	.incbin "data/layouts/OCEANVIEW_CITY_0_3/map.bin"

	.align 2
OCEANVIEW_CITY_0_3_Layout::
    .4byte    0x00000028  @Map Width
    .4byte    0x0000003C  @Map Height
    .4byte    OCEANVIEW_CITY_0_3_MapBorder  @Border Data
    .4byte    OCEANVIEW_CITY_0_3_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_OCEANVIEW_CITY_0_3_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_OCEANVIEW_CITY_0_3_SecondaryTileset  @Secondary Tileset
SERENITY_ISLE_0_4_MapBorder::
	.incbin "data/layouts/SERENITY_ISLE_0_4/border.bin"

SERENITY_ISLE_0_4_MapBlockdata::
	.incbin "data/layouts/SERENITY_ISLE_0_4/map.bin"

	.align 2
SERENITY_ISLE_0_4_Layout::
    .4byte    0x00000046  @Map Width
    .4byte    0x00000028  @Map Height
    .4byte    SERENITY_ISLE_0_4_MapBorder  @Border Data
    .4byte    SERENITY_ISLE_0_4_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SERENITY_ISLE_0_4_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SERENITY_ISLE_0_4_SecondaryTileset  @Secondary Tileset
CAPE_AZURE_0_5_MapBorder::
	.incbin "data/layouts/CAPE_AZURE_0_5/border.bin"

CAPE_AZURE_0_5_MapBlockdata::
	.incbin "data/layouts/CAPE_AZURE_0_5/map.bin"

	.align 2
CAPE_AZURE_0_5_Layout::
    .4byte    0x00000028  @Map Width
    .4byte    0x00000028  @Map Height
    .4byte    CAPE_AZURE_0_5_MapBorder  @Border Data
    .4byte    CAPE_AZURE_0_5_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CAPE_AZURE_0_5_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CAPE_AZURE_0_5_SecondaryTileset  @Secondary Tileset
PALMTREE_RESORT_0_6_MapBorder::
	.incbin "data/layouts/PALMTREE_RESORT_0_6/border.bin"

PALMTREE_RESORT_0_6_MapBlockdata::
	.incbin "data/layouts/PALMTREE_RESORT_0_6/map.bin"

	.align 2
PALMTREE_RESORT_0_6_Layout::
    .4byte    0x00000028  @Map Width
    .4byte    0x0000001E  @Map Height
    .4byte    PALMTREE_RESORT_0_6_MapBorder  @Border Data
    .4byte    PALMTREE_RESORT_0_6_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_PALMTREE_RESORT_0_6_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_PALMTREE_RESORT_0_6_SecondaryTileset  @Secondary Tileset
DARKWOOD_TOWN_0_7_MapBorder::
	.incbin "data/layouts/DARKWOOD_TOWN_0_7/border.bin"

DARKWOOD_TOWN_0_7_MapBlockdata::
	.incbin "data/layouts/DARKWOOD_TOWN_0_7/map.bin"

	.align 2
DARKWOOD_TOWN_0_7_Layout::
    .4byte    0x00000037  @Map Width
    .4byte    0x0000001A  @Map Height
    .4byte    DARKWOOD_TOWN_0_7_MapBorder  @Border Data
    .4byte    DARKWOOD_TOWN_0_7_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_DARKWOOD_TOWN_0_7_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_DARKWOOD_TOWN_0_7_SecondaryTileset  @Secondary Tileset
TUNOD_LEAGUE_0_8_MapBorder::
	.incbin "data/layouts/TUNOD_LEAGUE_0_8/border.bin"

TUNOD_LEAGUE_0_8_MapBlockdata::
	.incbin "data/layouts/TUNOD_LEAGUE_0_8/map.bin"

	.align 2
TUNOD_LEAGUE_0_8_Layout::
    .4byte    0x0000001E  @Map Width
    .4byte    0x00000014  @Map Height
    .4byte    TUNOD_LEAGUE_0_8_MapBorder  @Border Data
    .4byte    TUNOD_LEAGUE_0_8_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_TUNOD_LEAGUE_0_8_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_TUNOD_LEAGUE_0_8_SecondaryTileset  @Secondary Tileset
GLENWOOD_TOWN_0_9_MapBorder::
	.incbin "data/layouts/GLENWOOD_TOWN_0_9/border.bin"

GLENWOOD_TOWN_0_9_MapBlockdata::
	.incbin "data/layouts/GLENWOOD_TOWN_0_9/map.bin"

	.align 2
GLENWOOD_TOWN_0_9_Layout::
    .4byte    0x00000026  @Map Width
    .4byte    0x0000001C  @Map Height
    .4byte    GLENWOOD_TOWN_0_9_MapBorder  @Border Data
    .4byte    GLENWOOD_TOWN_0_9_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_GLENWOOD_TOWN_0_9_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_GLENWOOD_TOWN_0_9_SecondaryTileset  @Secondary Tileset
STORMY_CITY_0_12_MapBorder::
	.incbin "data/layouts/STORMY_CITY_0_12/border.bin"

STORMY_CITY_0_12_MapBlockdata::
	.incbin "data/layouts/STORMY_CITY_0_12/map.bin"

	.align 2
STORMY_CITY_0_12_Layout::
    .4byte    0x00000028  @Map Width
    .4byte    0x0000002A  @Map Height
    .4byte    STORMY_CITY_0_12_MapBorder  @Border Data
    .4byte    STORMY_CITY_0_12_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_STORMY_CITY_0_12_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_STORMY_CITY_0_12_SecondaryTileset  @Secondary Tileset
GEMINITE_VILLAGE_0_13_MapBorder::
	.incbin "data/layouts/GEMINITE_VILLAGE_0_13/border.bin"

GEMINITE_VILLAGE_0_13_MapBlockdata::
	.incbin "data/layouts/GEMINITE_VILLAGE_0_13/map.bin"

	.align 2
GEMINITE_VILLAGE_0_13_Layout::
    .4byte    0x0000003C  @Map Width
    .4byte    0x00000024  @Map Height
    .4byte    GEMINITE_VILLAGE_0_13_MapBorder  @Border Data
    .4byte    GEMINITE_VILLAGE_0_13_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_GEMINITE_VILLAGE_0_13_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_GEMINITE_VILLAGE_0_13_SecondaryTileset  @Secondary Tileset
CHOCCO_TOWN_0_15_MapBorder::
	.incbin "data/layouts/CHOCCO_TOWN_0_15/border.bin"

CHOCCO_TOWN_0_15_MapBlockdata::
	.incbin "data/layouts/CHOCCO_TOWN_0_15/map.bin"

	.align 2
CHOCCO_TOWN_0_15_Layout::
    .4byte    0x0000001E  @Map Width
    .4byte    0x00000028  @Map Height
    .4byte    CHOCCO_TOWN_0_15_MapBorder  @Border Data
    .4byte    CHOCCO_TOWN_0_15_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_CHOCCO_TOWN_0_15_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_CHOCCO_TOWN_0_15_SecondaryTileset  @Secondary Tileset
SPRINGSIDE_PATH_0_16_MapBorder::
	.incbin "data/layouts/SPRINGSIDE_PATH_0_16/border.bin"

SPRINGSIDE_PATH_0_16_MapBlockdata::
	.incbin "data/layouts/SPRINGSIDE_PATH_0_16/map.bin"

	.align 2
SPRINGSIDE_PATH_0_16_Layout::
    .4byte    0x00000030  @Map Width
    .4byte    0x0000001A  @Map Height
    .4byte    SPRINGSIDE_PATH_0_16_MapBorder  @Border Data
    .4byte    SPRINGSIDE_PATH_0_16_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_SPRINGSIDE_PATH_0_16_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_SPRINGSIDE_PATH_0_16_SecondaryTileset  @Secondary Tileset
FOREST_PASS_0_17_MapBorder::
	.incbin "data/layouts/FOREST_PASS_0_17/border.bin"

FOREST_PASS_0_17_MapBlockdata::
	.incbin "data/layouts/FOREST_PASS_0_17/map.bin"

	.align 2
FOREST_PASS_0_17_Layout::
    .4byte    0x00000032  @Map Width
    .4byte    0x0000001C  @Map Height
    .4byte    FOREST_PASS_0_17_MapBorder  @Border Data
    .4byte    FOREST_PASS_0_17_MapBlockdata  @Map data / Movement Permissons
    .4byte    gTileset_FOREST_PASS_0_17_PrimaryTileset  @Primary Tileset
    .4byte    gTileset_FOREST_PASS_0_17_SecondaryTileset  @Secondary Tileset
