	.align 2
gTilesetTiles_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/15.gbapal"

	.align 2
gTilesetTiles_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dewford::
	.incbin "data/tilesets/secondary/dewford/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dewford::
	.incbin "data/tilesets/secondary/dewford/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/15.gbapal"

	.align 2
gTilesetTiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Slateport::
	.incbin "data/tilesets/secondary/slateport/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mauville::
	.incbin "data/tilesets/secondary/mauville/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fortree::
	.incbin "data/tilesets/secondary/fortree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/15.gbapal"

	.align 2
gTilesetTiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/15.gbapal"

	.align 2
gTilesetTiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/15.gbapal"

	.align 2
gTilesetTiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideBuilding::
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

	.align 2
gTilesetTiles_Shop::
	.incbin "data/tilesets/secondary/shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Shop::
	.incbin "data/tilesets/secondary/shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/15.gbapal"

	.align 2
gTilesetTiles_Cave::
	.incbin "data/tilesets/secondary/cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Cave::
	.incbin "data/tilesets/secondary/cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_Unused1::
	.incbin "data/tilesets/secondary/unused_1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Unused1::
	.incbin "data/tilesets/secondary/unused_1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/15.gbapal"

	.align 2
gTilesetTiles_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/15.gbapal"

	.align 2
gTilesetTiles_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/secondary/cable_club/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/15.gbapal"

	.align 2
gTilesetTiles_Facility::
	.incbin "data/tilesets/secondary/facility/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Facility::
	.incbin "data/tilesets/secondary/facility/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/15.gbapal"

	.align 2
gTilesetTiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/brown_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBrownCave::
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/tree/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseTree::
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/shrub/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseShrub::
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/blue_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBlueCave::
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseYellowCave::
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/red_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseRedCave::
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBaseBrownCave::
	.incbin "data/tilesets/secondary/secret_base/brown_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseTree::
	.incbin "data/tilesets/secondary/secret_base/tree/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseShrub::
	.incbin "data/tilesets/secondary/secret_base/shrub/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseBlueCave::
	.incbin "data/tilesets/secondary/secret_base/blue_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseYellowCave::
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseRedCave::
	.incbin "data/tilesets/secondary/secret_base/red_cave/tiles.4bpp"

	.align 2
gTilesetTiles_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/15.gbapal"

	.align 2
gTilesetTiles_Contest::
	.incbin "data/tilesets/secondary/contest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Contest::
	.incbin "data/tilesets/secondary/contest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/15.gbapal"

	.align 2
gTilesetTiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lab::
	.incbin "data/tilesets/secondary/lab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lab::
	.incbin "data/tilesets/secondary/lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/15.gbapal"

	.align 2
gTilesetTiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Underwater::
	.incbin "data/tilesets/secondary/underwater/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/15.gbapal"

	.align 2
gTilesetTiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_Unused2::
	.incbin "data/tilesets/secondary/unused_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Unused2::
	.incbin "data/tilesets/secondary/unused_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBase::
	.incbin "data/tilesets/primary/secret_base/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/primary/secret_base/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_SecretBase::
	.incbin "data/tilesets/primary/secret_base/palettes/00.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/01.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/02.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/03.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/04.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/05.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/06.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/07.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/08.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/09.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/10.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/11.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/12.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/13.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/14.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/15.gbapal"

	.align 2
gTilesetTiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/15.gbapal"

	.align 2
gTilesetTiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/15.gbapal"

	.align 2
gTilesetTiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/15.gbapal"

	.align 2
gTilesetTiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/15.gbapal"

	.align 2
gTilesetPalettes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glazed_general::
	.incbin "data/tilesets/primary/glazed_general/palettes/00.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/01.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/02.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/03.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/04.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/05.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/06.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/07.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/08.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/09.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/10.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/11.gbapal"
	.incbin "data/tilesets/primary/glazed_general/palettes/12.gbapal"

	.align 2
gTilesetTiles_glazed_general::
	.incbin "data/tilesets/primary/glazed_general/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glazed_cave::
	.incbin "data/tilesets/primary/glazed_cave/palettes/00.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/01.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/02.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/03.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/04.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/05.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/06.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/07.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/08.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/09.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/10.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/11.gbapal"
	.incbin "data/tilesets/primary/glazed_cave/palettes/12.gbapal"

	.align 2
gTilesetTiles_glazed_cave::
	.incbin "data/tilesets/primary/glazed_cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glazed_building::
	.incbin "data/tilesets/primary/glazed_building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/glazed_building/palettes/12.gbapal"

	.align 2
gTilesetTiles_glazed_building::
	.incbin "data/tilesets/primary/glazed_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glenwood::
	.incbin "data/tilesets/secondary/glenwood/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/glenwood/palettes/12.gbapal"

	.align 2
gTilesetTiles_glenwood::
	.incbin "data/tilesets/secondary/glenwood/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_oceanview::
	.incbin "data/tilesets/secondary/oceanview/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/oceanview/palettes/12.gbapal"

	.align 2
gTilesetTiles_oceanview::
	.incbin "data/tilesets/secondary/oceanview/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_serenity::
	.incbin "data/tilesets/secondary/serenity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/serenity/palettes/12.gbapal"

	.align 2
gTilesetTiles_serenity::
	.incbin "data/tilesets/secondary/serenity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_seaspray::
	.incbin "data/tilesets/secondary/seaspray/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seaspray/palettes/12.gbapal"

	.align 2
gTilesetTiles_seaspray::
	.incbin "data/tilesets/secondary/seaspray/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_mahogany::
	.incbin "data/tilesets/secondary/mahogany/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mahogany/palettes/12.gbapal"

	.align 2
gTilesetTiles_mahogany::
	.incbin "data/tilesets/secondary/mahogany/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_northcoast::
	.incbin "data/tilesets/secondary/northcoast/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/northcoast/palettes/12.gbapal"

	.align 2
gTilesetTiles_northcoast::
	.incbin "data/tilesets/secondary/northcoast/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_cape_azure::
	.incbin "data/tilesets/secondary/cape_azure/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cape_azure/palettes/12.gbapal"

	.align 2
gTilesetTiles_cape_azure::
	.incbin "data/tilesets/secondary/cape_azure/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_palmtree::
	.incbin "data/tilesets/secondary/palmtree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/palmtree/palettes/12.gbapal"

	.align 2
gTilesetTiles_palmtree::
	.incbin "data/tilesets/secondary/palmtree/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_stormy::
	.incbin "data/tilesets/secondary/stormy/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/stormy/palettes/12.gbapal"

	.align 2
gTilesetTiles_stormy::
	.incbin "data/tilesets/secondary/stormy/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_league_outside::
	.incbin "data/tilesets/secondary/league_outside/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/league_outside/palettes/12.gbapal"

	.align 2
gTilesetTiles_league_outside::
	.incbin "data/tilesets/secondary/league_outside/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_new_bark::
	.incbin "data/tilesets/secondary/new_bark/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/12.gbapal"

	.align 2
gTilesetTiles_new_bark::
	.incbin "data/tilesets/secondary/new_bark/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_darkwood::
	.incbin "data/tilesets/secondary/darkwood/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/darkwood/palettes/12.gbapal"

	.align 2
gTilesetTiles_darkwood::
	.incbin "data/tilesets/secondary/darkwood/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_goldenrod::
	.incbin "data/tilesets/secondary/goldenrod/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/12.gbapal"

	.align 2
gTilesetTiles_goldenrod::
	.incbin "data/tilesets/secondary/goldenrod/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_azalea::
	.incbin "data/tilesets/secondary/azalea/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/12.gbapal"

	.align 2
gTilesetTiles_azalea::
	.incbin "data/tilesets/secondary/azalea/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glazed_mart::
	.incbin "data/tilesets/secondary/glazed_mart/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/glazed_mart/palettes/12.gbapal"

	.align 2
gTilesetTiles_glazed_mart::
	.incbin "data/tilesets/secondary/glazed_mart/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glazed_pokemoncenter::
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/palettes/12.gbapal"

	.align 2
gTilesetTiles_glazed_pokemoncenter::
	.incbin "data/tilesets/secondary/glazed_pokemoncenter/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_cave1::
	.incbin "data/tilesets/secondary/cave1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cave1/palettes/12.gbapal"

	.align 2
gTilesetTiles_cave1::
	.incbin "data/tilesets/secondary/cave1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_olivine::
	.incbin "data/tilesets/secondary/olivine/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/olivine/palettes/12.gbapal"

	.align 2
gTilesetTiles_olivine::
	.incbin "data/tilesets/secondary/olivine/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_stratus_lab::
	.incbin "data/tilesets/secondary/stratus_lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/stratus_lab/palettes/12.gbapal"

	.align 2
gTilesetTiles_stratus_lab::
	.incbin "data/tilesets/secondary/stratus_lab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_church::
	.incbin "data/tilesets/secondary/church/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/church/palettes/12.gbapal"

	.align 2
gTilesetTiles_church::
	.incbin "data/tilesets/secondary/church/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_whitewood::
	.incbin "data/tilesets/secondary/whitewood/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/whitewood/palettes/12.gbapal"

	.align 2
gTilesetTiles_whitewood::
	.incbin "data/tilesets/secondary/whitewood/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_violet::
	.incbin "data/tilesets/secondary/violet/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/12.gbapal"

	.align 2
gTilesetTiles_violet::
	.incbin "data/tilesets/secondary/violet/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_cianvine_bridge::
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cianvine_bridge/palettes/12.gbapal"

	.align 2
gTilesetTiles_cianvine_bridge::
	.incbin "data/tilesets/secondary/cianvine_bridge/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_plant::
	.incbin "data/tilesets/secondary/plant/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/plant/palettes/12.gbapal"

	.align 2
gTilesetTiles_plant::
	.incbin "data/tilesets/secondary/plant/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_forest::
	.incbin "data/tilesets/secondary/forest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/12.gbapal"

	.align 2
gTilesetTiles_forest::
	.incbin "data/tilesets/secondary/forest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_gym1::
	.incbin "data/tilesets/secondary/gym1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gym1/palettes/12.gbapal"

	.align 2
gTilesetTiles_gym1::
	.incbin "data/tilesets/secondary/gym1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_gym2::
	.incbin "data/tilesets/secondary/gym2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gym2/palettes/12.gbapal"

	.align 2
gTilesetTiles_gym2::
	.incbin "data/tilesets/secondary/gym2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_gym3::
	.incbin "data/tilesets/secondary/gym3/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gym3/palettes/12.gbapal"

	.align 2
gTilesetTiles_gym3::
	.incbin "data/tilesets/secondary/gym3/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_gym4::
	.incbin "data/tilesets/secondary/gym4/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gym4/palettes/12.gbapal"

	.align 2
gTilesetTiles_gym4::
	.incbin "data/tilesets/secondary/gym4/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_gym5::
	.incbin "data/tilesets/secondary/gym5/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gym5/palettes/12.gbapal"

	.align 2
gTilesetTiles_gym5::
	.incbin "data/tilesets/secondary/gym5/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_gym6::
	.incbin "data/tilesets/secondary/gym6/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gym6/palettes/12.gbapal"

	.align 2
gTilesetTiles_gym6::
	.incbin "data/tilesets/secondary/gym6/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_gym7::
	.incbin "data/tilesets/secondary/gym7/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gym7/palettes/12.gbapal"

	.align 2
gTilesetTiles_gym7::
	.incbin "data/tilesets/secondary/gym7/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_gym8::
	.incbin "data/tilesets/secondary/gym8/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gym8/palettes/12.gbapal"

	.align 2
gTilesetTiles_gym8::
	.incbin "data/tilesets/secondary/gym8/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_gym9::
	.incbin "data/tilesets/secondary/gym9/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gym9/palettes/12.gbapal"

	.align 2
gTilesetTiles_gym9::
	.incbin "data/tilesets/secondary/gym9/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_swamp::
	.incbin "data/tilesets/secondary/swamp/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/swamp/palettes/12.gbapal"

	.align 2
gTilesetTiles_swamp::
	.incbin "data/tilesets/secondary/swamp/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_villa::
	.incbin "data/tilesets/secondary/villa/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/villa/palettes/12.gbapal"

	.align 2
gTilesetTiles_villa::
	.incbin "data/tilesets/secondary/villa/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_stratus_peak::
	.incbin "data/tilesets/secondary/stratus_peak/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/stratus_peak/palettes/12.gbapal"

	.align 2
gTilesetTiles_stratus_peak::
	.incbin "data/tilesets/secondary/stratus_peak/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_rankor_cave::
	.incbin "data/tilesets/secondary/rankor_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rankor_cave/palettes/12.gbapal"

	.align 2
gTilesetTiles_rankor_cave::
	.incbin "data/tilesets/secondary/rankor_cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glazed_contest::
	.incbin "data/tilesets/secondary/glazed_contest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/glazed_contest/palettes/12.gbapal"

	.align 2
gTilesetTiles_glazed_contest::
	.incbin "data/tilesets/secondary/glazed_contest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_cainwood::
	.incbin "data/tilesets/secondary/cainwood/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cainwood/palettes/12.gbapal"

	.align 2
gTilesetTiles_cainwood::
	.incbin "data/tilesets/secondary/cainwood/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_town1::
	.incbin "data/tilesets/secondary/town1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/town1/palettes/12.gbapal"

	.align 2
gTilesetTiles_town1::
	.incbin "data/tilesets/secondary/town1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glazed_lab::
	.incbin "data/tilesets/secondary/glazed_lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/glazed_lab/palettes/12.gbapal"

	.align 2
gTilesetTiles_glazed_lab::
	.incbin "data/tilesets/secondary/glazed_lab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_seafloor::
	.incbin "data/tilesets/secondary/seafloor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seafloor/palettes/12.gbapal"

	.align 2
gTilesetTiles_seafloor::
	.incbin "data/tilesets/secondary/seafloor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_reefen::
	.incbin "data/tilesets/secondary/reefen/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/reefen/palettes/12.gbapal"

	.align 2
gTilesetTiles_reefen::
	.incbin "data/tilesets/secondary/reefen/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_town2::
	.incbin "data/tilesets/secondary/town2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/town2/palettes/12.gbapal"

	.align 2
gTilesetTiles_town2::
	.incbin "data/tilesets/secondary/town2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_kolo::
	.incbin "data/tilesets/secondary/kolo/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kolo/palettes/12.gbapal"

	.align 2
gTilesetTiles_kolo::
	.incbin "data/tilesets/secondary/kolo/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_alpha::
	.incbin "data/tilesets/secondary/alpha/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/alpha/palettes/12.gbapal"

	.align 2
gTilesetTiles_alpha::
	.incbin "data/tilesets/secondary/alpha/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_reign::
	.incbin "data/tilesets/secondary/reign/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/reign/palettes/12.gbapal"

	.align 2
gTilesetTiles_reign::
	.incbin "data/tilesets/secondary/reign/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_league_building::
	.incbin "data/tilesets/secondary/league_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/league_building/palettes/12.gbapal"

	.align 2
gTilesetTiles_league_building::
	.incbin "data/tilesets/secondary/league_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_trainer_isle::
	.incbin "data/tilesets/secondary/trainer_isle/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_isle/palettes/12.gbapal"

	.align 2
gTilesetTiles_trainer_isle::
	.incbin "data/tilesets/secondary/trainer_isle/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ruins_of_alph::
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/12.gbapal"

	.align 2
gTilesetTiles_ruins_of_alph::
	.incbin "data/tilesets/secondary/ruins_of_alph/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glazed_dock::
	.incbin "data/tilesets/secondary/glazed_dock/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/glazed_dock/palettes/12.gbapal"

	.align 2
gTilesetTiles_glazed_dock::
	.incbin "data/tilesets/secondary/glazed_dock/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_undersea_grotto::
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/undersea_grotto/palettes/12.gbapal"

	.align 2
gTilesetTiles_undersea_grotto::
	.incbin "data/tilesets/secondary/undersea_grotto/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_glenwood2::
	.incbin "data/tilesets/secondary/glenwood2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/glenwood2/palettes/12.gbapal"

	.align 2
gTilesetTiles_glenwood2::
	.incbin "data/tilesets/secondary/glenwood2/tiles.4bpp.lz"
