	.align 2
gTileset_General::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_General
	.4byte gTilesetPalettes_General
	.4byte gMetatiles_General
	.4byte gMetatileAttributes_General
	.4byte InitTilesetAnim_General

	.align 2
gTileset_Petalburg::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Petalburg
	.4byte gTilesetPalettes_Petalburg
	.4byte gMetatiles_Petalburg
	.4byte gMetatileAttributes_Petalburg
	.4byte InitTilesetAnim_Petalburg

	.align 2
gTileset_Rustboro::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Rustboro
	.4byte gTilesetPalettes_Rustboro
	.4byte gMetatiles_Rustboro
	.4byte gMetatileAttributes_Rustboro
	.4byte InitTilesetAnim_Rustboro

	.align 2
gTileset_Dewford::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Dewford
	.4byte gTilesetPalettes_Dewford
	.4byte gMetatiles_Dewford
	.4byte gMetatileAttributes_Dewford
	.4byte InitTilesetAnim_Dewford

	.align 2
gTileset_Slateport::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Slateport
	.4byte gTilesetPalettes_Slateport
	.4byte gMetatiles_Slateport
	.4byte gMetatileAttributes_Slateport
	.4byte InitTilesetAnim_Slateport

	.align 2
gTileset_Mauville::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mauville
	.4byte gTilesetPalettes_Mauville
	.4byte gMetatiles_Mauville
	.4byte gMetatileAttributes_Mauville
	.4byte InitTilesetAnim_Mauville

	.align 2
gTileset_Lavaridge::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lavaridge
	.4byte gTilesetPalettes_Lavaridge
	.4byte gMetatiles_Lavaridge
	.4byte gMetatileAttributes_Lavaridge
	.4byte InitTilesetAnim_Lavaridge

	.align 2
gTileset_Fallarbor::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fallarbor
	.4byte gTilesetPalettes_Fallarbor
	.4byte gMetatiles_Fallarbor
	.4byte gMetatileAttributes_Fallarbor
	.4byte InitTilesetAnim_Fallarbor

	.align 2
gTileset_Fortree::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fortree
	.4byte gTilesetPalettes_Fortree
	.4byte gMetatiles_Fortree
	.4byte gMetatileAttributes_Fortree
	.4byte InitTilesetAnim_Fortree

	.align 2
gTileset_Lilycove::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lilycove
	.4byte gTilesetPalettes_Lilycove
	.4byte gMetatiles_Lilycove
	.4byte gMetatileAttributes_Lilycove
	.4byte InitTilesetAnim_Lilycove

	.align 2
gTileset_Mossdeep::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mossdeep
	.4byte gTilesetPalettes_Mossdeep
	.4byte gMetatiles_Mossdeep
	.4byte gMetatileAttributes_Mossdeep
	.4byte InitTilesetAnim_Mossdeep

	.align 2
gTileset_EverGrande::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EverGrande
	.4byte gTilesetPalettes_EverGrande
	.4byte gMetatiles_EverGrande
	.4byte gMetatileAttributes_EverGrande
	.4byte InitTilesetAnim_EverGrande

	.align 2
gTileset_Pacifidlog::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Pacifidlog
	.4byte gTilesetPalettes_Pacifidlog
	.4byte gMetatiles_Pacifidlog
	.4byte gMetatileAttributes_Pacifidlog
	.4byte InitTilesetAnim_Pacifidlog

	.align 2
gTileset_Sootopolis::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Sootopolis
	.4byte gTilesetPalettes_Sootopolis
	.4byte gMetatiles_Sootopolis
	.4byte gMetatileAttributes_Sootopolis
	.4byte InitTilesetAnim_Sootopolis

	.align 2
gTileset_BattleFrontierOutsideWest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideWest
	.4byte gTilesetPalettes_BattleFrontierOutsideWest
	.4byte gMetatiles_BattleFrontierOutsideWest
	.4byte gMetatileAttributes_BattleFrontierOutsideWest
	.4byte InitTilesetAnim_BattleFrontierOutsideWest

	.align 2
gTileset_BattleFrontierOutsideEast::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideEast
	.4byte gTilesetPalettes_BattleFrontierOutsideEast
	.4byte gMetatiles_BattleFrontierOutsideEast
	.4byte gMetatileAttributes_BattleFrontierOutsideEast
	.4byte InitTilesetAnim_BattleFrontierOutsideEast

	.align 2
gTileset_Building::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideBuilding
	.4byte gTilesetPalettes_InsideBuilding
	.4byte gMetatiles_InsideBuilding
	.4byte gMetatileAttributes_InsideBuilding
	.4byte InitTilesetAnim_Building

	.align 2
gTileset_Shop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Shop
	.4byte gTilesetPalettes_Shop
	.4byte gMetatiles_Shop
	.4byte gMetatileAttributes_Shop
	.4byte NULL @ animation callback

	.align 2
gTileset_PokemonCenter::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonCenter
	.4byte gTilesetPalettes_PokemonCenter
	.4byte gMetatiles_PokemonCenter
	.4byte gMetatileAttributes_PokemonCenter
	.4byte NULL @ animation callback

	.align 2
gTileset_Cave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Cave
	.4byte gTilesetPalettes_Cave
	.4byte gMetatiles_Cave
	.4byte gMetatileAttributes_Cave
	.4byte InitTilesetAnim_Cave

	.align 2
gTileset_PokemonSchool::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonSchool
	.4byte gTilesetPalettes_PokemonSchool
	.4byte gMetatiles_PokemonSchool
	.4byte gMetatileAttributes_PokemonSchool
	.4byte NULL @ animation callback

	.align 2
gTileset_PokemonFanClub::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonFanClub
	.4byte gTilesetPalettes_PokemonFanClub
	.4byte gMetatiles_PokemonFanClub
	.4byte gMetatileAttributes_PokemonFanClub
	.4byte NULL @ animation callback

	.align 2
gTileset_Unused1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Unused1
	.4byte gTilesetPalettes_Unused1
	.4byte gMetatiles_Unused1
	.4byte gMetatileAttributes_Unused1
	.4byte NULL @ animation callback

	.align 2
gTileset_MeteorFalls::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MeteorFalls
	.4byte gTilesetPalettes_MeteorFalls
	.4byte gMetatiles_MeteorFalls
	.4byte gMetatileAttributes_MeteorFalls
	.4byte NULL @ animation callback

	.align 2
gTileset_OceanicMuseum::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_OceanicMuseum
	.4byte gTilesetPalettes_OceanicMuseum
	.4byte gMetatiles_OceanicMuseum
	.4byte gMetatileAttributes_OceanicMuseum
	.4byte NULL @ animation callback

	.align 2
gTileset_CableClub::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_CableClub
	.4byte gTilesetPalettes_CableClub
	.4byte gMetatiles_CableClub
	.4byte gMetatileAttributes_CableClub
	.4byte NULL @ animation callback

	.align 2
gTileset_SeashoreHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SeashoreHouse
	.4byte gTilesetPalettes_SeashoreHouse
	.4byte gMetatiles_SeashoreHouse
	.4byte gMetatileAttributes_SeashoreHouse
	.4byte NULL @ animation callback

	.align 2
gTileset_PrettyPetalFlowerShop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PrettyPetalFlowerShop
	.4byte gTilesetPalettes_PrettyPetalFlowerShop
	.4byte gMetatiles_PrettyPetalFlowerShop
	.4byte gMetatileAttributes_PrettyPetalFlowerShop
	.4byte NULL @ animation callback

	.align 2
gTileset_PokemonDayCare::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonDayCare
	.4byte gTilesetPalettes_PokemonDayCare
	.4byte gMetatiles_PokemonDayCare
	.4byte gMetatileAttributes_PokemonDayCare
	.4byte NULL @ animation callback

	.align 2
gTileset_Facility::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Facility
	.4byte gTilesetPalettes_Facility
	.4byte gMetatiles_Facility
	.4byte gMetatileAttributes_Facility
	.4byte NULL @ animation callback

	.align 2
gTileset_BikeShop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BikeShop
	.4byte gTilesetPalettes_BikeShop
	.4byte gMetatiles_BikeShop
	.4byte gMetatileAttributes_BikeShop
	.4byte InitTilesetAnim_BikeShop

	.align 2
gTileset_RusturfTunnel::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RusturfTunnel
	.4byte gTilesetPalettes_RusturfTunnel
	.4byte gMetatiles_RusturfTunnel
	.4byte gMetatileAttributes_RusturfTunnel
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseBrownCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBrownCave
	.4byte gTilesetPalettes_SecretBaseBrownCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseTree::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseTree
	.4byte gTilesetPalettes_SecretBaseTree
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseShrub::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseShrub
	.4byte gTilesetPalettes_SecretBaseShrub
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseBlueCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBlueCave
	.4byte gTilesetPalettes_SecretBaseBlueCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseYellowCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseYellowCave
	.4byte gTilesetPalettes_SecretBaseYellowCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseRedCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseRedCave
	.4byte gTilesetPalettes_SecretBaseRedCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_InsideOfTruck::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideOfTruck
	.4byte gTilesetPalettes_InsideOfTruck
	.4byte gMetatiles_InsideOfTruck
	.4byte gMetatileAttributes_InsideOfTruck
	.4byte NULL @ animation callback

	.align 2
gTileset_Unused2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Unused2
	.4byte gTilesetPalettes_Unused2
	.4byte gMetatiles_Unused2
	.4byte gMetatileAttributes_Unused2
	.4byte NULL @ animation callback

	.align 2
gTileset_Contest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Contest
	.4byte gTilesetPalettes_Contest
	.4byte gMetatiles_Contest
	.4byte gMetatileAttributes_Contest
	.4byte NULL @ animation callback

	.align 2
gTileset_LilycoveMuseum::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LilycoveMuseum
	.4byte gTilesetPalettes_LilycoveMuseum
	.4byte gMetatiles_LilycoveMuseum
	.4byte gMetatileAttributes_LilycoveMuseum
	.4byte NULL @ animation callback

	.align 2
gTileset_BrendansMaysHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BrendansMaysHouse
	.4byte gTilesetPalettes_BrendansMaysHouse
	.4byte gMetatiles_BrendansMaysHouse
	.4byte gMetatileAttributes_BrendansMaysHouse
	.4byte NULL @ animation callback

	.align 2
gTileset_Lab::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lab
	.4byte gTilesetPalettes_Lab
	.4byte gMetatiles_Lab
	.4byte gMetatileAttributes_Lab
	.4byte NULL @ animation callback

	.align 2
gTileset_Underwater::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Underwater
	.4byte gTilesetPalettes_Underwater
	.4byte gMetatiles_Underwater
	.4byte gMetatileAttributes_Underwater
	.4byte InitTilesetAnim_Underwater

	.align 2
gTileset_PetalburgGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PetalburgGym
	.4byte gTilesetPalettes_PetalburgGym
	.4byte gMetatiles_PetalburgGym
	.4byte gMetatileAttributes_PetalburgGym
	.4byte NULL @ animation callback

	.align 2
gTileset_SootopolisGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SootopolisGym
	.4byte gTilesetPalettes_SootopolisGym
	.4byte gMetatiles_SootopolisGym
	.4byte gMetatileAttributes_SootopolisGym
	.4byte InitTilesetAnim_SootopolisGym

	.align 2
gTileset_GenericBuilding::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_GenericBuilding
	.4byte gTilesetPalettes_GenericBuilding
	.4byte gMetatiles_GenericBuilding
	.4byte gMetatileAttributes_GenericBuilding
	.4byte NULL @ animation callback

	.align 2
gTileset_MauvilleGameCorner::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MauvilleGameCorner
	.4byte gTilesetPalettes_MauvilleGameCorner
	.4byte gMetatiles_MauvilleGameCorner
	.4byte gMetatileAttributes_MauvilleGameCorner
	.4byte NULL @ animation callback

	.align 2
gTileset_RustboroGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RustboroGym
	.4byte gTilesetPalettes_RustboroGym
	.4byte gMetatiles_RustboroGym
	.4byte gMetatileAttributes_RustboroGym
	.4byte NULL @ animation callback

	.align 2
gTileset_DewfordGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_DewfordGym
	.4byte gTilesetPalettes_DewfordGym
	.4byte gMetatiles_DewfordGym
	.4byte gMetatileAttributes_DewfordGym
	.4byte NULL @ animation callback

	.align 2
gTileset_MauvilleGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MauvilleGym
	.4byte gTilesetPalettes_MauvilleGym
	.4byte gMetatiles_MauvilleGym
	.4byte gMetatileAttributes_MauvilleGym
	.4byte InitTilesetAnim_MauvilleGym

	.align 2
gTileset_LavaridgeGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LavaridgeGym
	.4byte gTilesetPalettes_LavaridgeGym
	.4byte gMetatiles_LavaridgeGym
	.4byte gMetatileAttributes_LavaridgeGym
	.4byte NULL @ animation callback

	.align 2
gTileset_TrickHousePuzzle::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrickHousePuzzle
	.4byte gTilesetPalettes_TrickHousePuzzle
	.4byte gMetatiles_TrickHousePuzzle
	.4byte gMetatileAttributes_TrickHousePuzzle
	.4byte NULL @ animation callback

	.align 2
gTileset_FortreeGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_FortreeGym
	.4byte gTilesetPalettes_FortreeGym
	.4byte gMetatiles_FortreeGym
	.4byte gMetatileAttributes_FortreeGym
	.4byte NULL @ animation callback

	.align 2
gTileset_MossdeepGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGym
	.4byte gTilesetPalettes_MossdeepGym
	.4byte gMetatiles_MossdeepGym
	.4byte gMetatileAttributes_MossdeepGym
	.4byte NULL @ animation callback

	.align 2
gTileset_InsideShip::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideShip
	.4byte gTilesetPalettes_InsideShip
	.4byte gMetatiles_InsideShip
	.4byte gMetatileAttributes_InsideShip
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBase::
	.byte FALSE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBase
	.4byte gTilesetPalettes_SecretBase
	.4byte gMetatiles_SecretBasePrimary
	.4byte gMetatileAttributes_SecretBasePrimary
	.4byte NULL @ animation callback

	.align 2
gTilesetPointer_SecretBase::
	.4byte gTileset_SecretBase

	.align 2
gTilesetPointer_SecretBaseRedCave::
	.4byte gTileset_SecretBaseRedCave

	.align 2
gTileset_EliteFour::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EliteFour
	.4byte gTilesetPalettes_EliteFour
	.4byte gMetatiles_EliteFour
	.4byte gMetatileAttributes_EliteFour
	.4byte InitTilesetAnim_EliteFour

	.align 2
gTileset_BattleFrontier::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontier
	.4byte gTilesetPalettes_BattleFrontier
	.4byte gMetatiles_BattleFrontier
	.4byte gMetatileAttributes_BattleFrontier
	.4byte NULL @ animation callback

	.align 2
gTileset_BattlePalace::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePalace
	.4byte gTilesetPalettes_BattlePalace
	.4byte gMetatiles_BattlePalace
	.4byte gMetatileAttributes_BattlePalace
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleDome::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleDome
	.4byte gTilesetPalettes_BattleDome
	.4byte gMetatiles_BattleDome
	.4byte gMetatileAttributes_BattleDome
	.4byte InitTilesetAnim_BattleDome

	.align 2
gTileset_BattleFactory::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFactory
	.4byte gTilesetPalettes_BattleFactory
	.4byte gMetatiles_BattleFactory
	.4byte gMetatileAttributes_BattleFactory
	.4byte NULL @ animation callback

	.align 2
gTileset_BattlePike::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePike
	.4byte gTilesetPalettes_BattlePike
	.4byte gMetatiles_BattlePike
	.4byte gMetatileAttributes_BattlePike
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleArena::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleArena
	.4byte gTilesetPalettes_BattleArena
	.4byte gMetatiles_BattleArena
	.4byte gMetatileAttributes_BattleArena
	.4byte NULL @ animation callback

	.align 2
gTileset_BattlePyramid::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePyramid
	.4byte gTilesetPalettes_BattlePyramid
	.4byte gMetatiles_BattlePyramid
	.4byte gMetatileAttributes_BattlePyramid
	.4byte InitTilesetAnim_BattlePyramid

	.align 2
gTileset_MirageTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MirageTower
	.4byte gTilesetPalettes_MirageTower
	.4byte gMetatiles_MirageTower
	.4byte gMetatileAttributes_MirageTower
	.4byte NULL @ animation callback

	.align 2
gTileset_MossdeepGameCorner::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGameCorner
	.4byte gTilesetPalettes_MossdeepGameCorner
	.4byte gMetatiles_MossdeepGameCorner
	.4byte gMetatileAttributes_MossdeepGameCorner
	.4byte NULL @ animation callback

	.align 2
gTileset_IslandHarbor::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_IslandHarbor
	.4byte gTilesetPalettes_IslandHarbor
	.4byte gMetatiles_IslandHarbor
	.4byte gMetatileAttributes_IslandHarbor
	.4byte NULL @ animation callback

	.align 2
gTileset_TrainerHill::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrainerHill
	.4byte gTilesetPalettes_TrainerHill
	.4byte gMetatiles_TrainerHill
	.4byte gMetatileAttributes_TrainerHill
	.4byte NULL @ animation callback

	.align 2
gTileset_NavelRock::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_NavelRock
	.4byte gTilesetPalettes_NavelRock
	.4byte gMetatiles_NavelRock
	.4byte gMetatileAttributes_NavelRock
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleFrontierRankingHall::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierRankingHall
	.4byte gTilesetPalettes_BattleFrontierRankingHall
	.4byte gMetatiles_BattleFrontierRankingHall
	.4byte gMetatileAttributes_BattleFrontierRankingHall
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleTent::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleTent
	.4byte gTilesetPalettes_BattleTent
	.4byte gMetatiles_BattleTent
	.4byte gMetatileAttributes_BattleTent
	.4byte NULL @ animation callback

	.align 2
gTileset_MysteryEventsHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MysteryEventsHouse
	.4byte gTilesetPalettes_MysteryEventsHouse
	.4byte gMetatiles_MysteryEventsHouse
	.4byte gMetatileAttributes_MysteryEventsHouse
	.4byte NULL @ animation callback

	.align 2
gTileset_UnionRoom::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_UnionRoom
	.4byte gTilesetPalettes_UnionRoom
	.4byte gMetatiles_UnionRoom
	.4byte gMetatileAttributes_UnionRoom
	.4byte NULL @ animation callback

	.align 2
gTileset_glazed_general::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glazed_general
	.4byte gTilesetPalettes_glazed_general
	.4byte gMetatiles_glazed_general
	.4byte gMetatileAttributes_glazed_general
	.4byte InitTilesetAnim_General

	.align 2
gTileset_glazed_cave::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glazed_cave
	.4byte gTilesetPalettes_glazed_cave
	.4byte gMetatiles_glazed_cave
	.4byte gMetatileAttributes_glazed_cave
	.4byte NULL @ animation callback

	.align 2
gTileset_glazed_building::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glazed_building
	.4byte gTilesetPalettes_glazed_building
	.4byte gMetatiles_glazed_building
	.4byte gMetatileAttributes_glazed_building
	.4byte InitTilesetAnim_Building

	.align 2
gTileset_glenwood::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glenwood
	.4byte gTilesetPalettes_glenwood
	.4byte gMetatiles_glenwood
	.4byte gMetatileAttributes_glenwood
	.4byte NULL @ animation callback

	.align 2
gTileset_oceanview::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_oceanview
	.4byte gTilesetPalettes_oceanview
	.4byte gMetatiles_oceanview
	.4byte gMetatileAttributes_oceanview
	.4byte NULL

	.align 2
gTileset_serenity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_serenity
	.4byte gTilesetPalettes_serenity
	.4byte gMetatiles_serenity
	.4byte gMetatileAttributes_serenity
	.4byte NULL

	.align 2
gTileset_seaspray::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_seaspray
	.4byte gTilesetPalettes_seaspray
	.4byte gMetatiles_seaspray
	.4byte gMetatileAttributes_seaspray
	.4byte NULL

	.align 2
gTileset_mahogany::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_mahogany
	.4byte gTilesetPalettes_mahogany
	.4byte gMetatiles_mahogany
	.4byte gMetatileAttributes_mahogany
	.4byte NULL

	.align 2
gTileset_northcoast::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_northcoast
	.4byte gTilesetPalettes_northcoast
	.4byte gMetatiles_northcoast
	.4byte gMetatileAttributes_northcoast
	.4byte NULL

	.align 2
gTileset_cape_azure::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_cape_azure
	.4byte gTilesetPalettes_cape_azure
	.4byte gMetatiles_cape_azure
	.4byte gMetatileAttributes_cape_azure
	.4byte NULL

	.align 2
gTileset_palmtree::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_palmtree
	.4byte gTilesetPalettes_palmtree
	.4byte gMetatiles_palmtree
	.4byte gMetatileAttributes_palmtree
	.4byte NULL

	.align 2
gTileset_stormy::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_stormy
	.4byte gTilesetPalettes_stormy
	.4byte gMetatiles_stormy
	.4byte gMetatileAttributes_stormy
	.4byte NULL

	.align 2
gTileset_league_outside::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_league_outside
	.4byte gTilesetPalettes_league_outside
	.4byte gMetatiles_league_outside
	.4byte gMetatileAttributes_league_outside
	.4byte NULL

	.align 2
gTileset_new_bark::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_new_bark
	.4byte gTilesetPalettes_new_bark
	.4byte gMetatiles_new_bark
	.4byte gMetatileAttributes_new_bark
	.4byte NULL

	.align 2
gTileset_darkwood::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_darkwood
	.4byte gTilesetPalettes_darkwood
	.4byte gMetatiles_darkwood
	.4byte gMetatileAttributes_darkwood
	.4byte NULL

	.align 2
gTileset_goldenrod::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_goldenrod
	.4byte gTilesetPalettes_goldenrod
	.4byte gMetatiles_goldenrod
	.4byte gMetatileAttributes_goldenrod
	.4byte NULL

	.align 2
gTileset_azalea::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_azalea
	.4byte gTilesetPalettes_azalea
	.4byte gMetatiles_azalea
	.4byte gMetatileAttributes_azalea
	.4byte NULL

	.align 2
gTileset_glazed_mart::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glazed_mart
	.4byte gTilesetPalettes_glazed_mart
	.4byte gMetatiles_glazed_mart
	.4byte gMetatileAttributes_glazed_mart
	.4byte NULL

	.align 2
gTileset_glazed_pokemoncenter::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glazed_pokemoncenter
	.4byte gTilesetPalettes_glazed_pokemoncenter
	.4byte gMetatiles_glazed_pokemoncenter
	.4byte gMetatileAttributes_glazed_pokemoncenter
	.4byte NULL

	.align 2
gTileset_cave1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_cave1
	.4byte gTilesetPalettes_cave1
	.4byte gMetatiles_cave1
	.4byte gMetatileAttributes_cave1
	.4byte NULL

	.align 2
gTileset_olivine::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_olivine
	.4byte gTilesetPalettes_olivine
	.4byte gMetatiles_olivine
	.4byte gMetatileAttributes_olivine
	.4byte NULL

	.align 2
gTileset_stratus_lab::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_stratus_lab
	.4byte gTilesetPalettes_stratus_lab
	.4byte gMetatiles_stratus_lab
	.4byte gMetatileAttributes_stratus_lab
	.4byte NULL

	.align 2
gTileset_church::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_church
	.4byte gTilesetPalettes_church
	.4byte gMetatiles_church
	.4byte gMetatileAttributes_church
	.4byte NULL

	.align 2
gTileset_whitewood::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_whitewood
	.4byte gTilesetPalettes_whitewood
	.4byte gMetatiles_whitewood
	.4byte gMetatileAttributes_whitewood
	.4byte NULL

	.align 2
gTileset_violet::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_violet
	.4byte gTilesetPalettes_violet
	.4byte gMetatiles_violet
	.4byte gMetatileAttributes_violet
	.4byte NULL

	.align 2
gTileset_cianvine_bridge::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_cianvine_bridge
	.4byte gTilesetPalettes_cianvine_bridge
	.4byte gMetatiles_cianvine_bridge
	.4byte gMetatileAttributes_cianvine_bridge
	.4byte NULL

	.align 2
gTileset_plant::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_plant
	.4byte gTilesetPalettes_plant
	.4byte gMetatiles_plant
	.4byte gMetatileAttributes_plant
	.4byte NULL

	.align 2
gTileset_forest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_forest
	.4byte gTilesetPalettes_forest
	.4byte gMetatiles_forest
	.4byte gMetatileAttributes_forest
	.4byte NULL

	.align 2
gTileset_gym1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_gym1
	.4byte gTilesetPalettes_gym1
	.4byte gMetatiles_gym1
	.4byte gMetatileAttributes_gym1
	.4byte NULL

	.align 2
gTileset_gym2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_gym2
	.4byte gTilesetPalettes_gym2
	.4byte gMetatiles_gym2
	.4byte gMetatileAttributes_gym2
	.4byte NULL

	.align 2
gTileset_gym3::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_gym3
	.4byte gTilesetPalettes_gym3
	.4byte gMetatiles_gym3
	.4byte gMetatileAttributes_gym3
	.4byte NULL

	.align 2
gTileset_gym4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_gym4
	.4byte gTilesetPalettes_gym4
	.4byte gMetatiles_gym4
	.4byte gMetatileAttributes_gym4
	.4byte NULL

	.align 2
gTileset_gym5::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_gym5
	.4byte gTilesetPalettes_gym5
	.4byte gMetatiles_gym5
	.4byte gMetatileAttributes_gym5
	.4byte NULL

	.align 2
gTileset_gym6::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_gym6
	.4byte gTilesetPalettes_gym6
	.4byte gMetatiles_gym6
	.4byte gMetatileAttributes_gym6
	.4byte NULL

	.align 2
gTileset_gym7::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_gym7
	.4byte gTilesetPalettes_gym7
	.4byte gMetatiles_gym7
	.4byte gMetatileAttributes_gym7
	.4byte NULL

	.align 2
gTileset_gym8::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_gym8
	.4byte gTilesetPalettes_gym8
	.4byte gMetatiles_gym8
	.4byte gMetatileAttributes_gym8
	.4byte NULL

	.align 2
gTileset_gym9::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_gym9
	.4byte gTilesetPalettes_gym9
	.4byte gMetatiles_gym9
	.4byte gMetatileAttributes_gym9
	.4byte NULL

	.align 2
gTileset_swamp::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_swamp
	.4byte gTilesetPalettes_swamp
	.4byte gMetatiles_swamp
	.4byte gMetatileAttributes_swamp
	.4byte NULL

	.align 2
gTileset_villa::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_villa
	.4byte gTilesetPalettes_villa
	.4byte gMetatiles_villa
	.4byte gMetatileAttributes_villa
	.4byte NULL

	.align 2
gTileset_stratus_peak::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_stratus_peak
	.4byte gTilesetPalettes_stratus_peak
	.4byte gMetatiles_stratus_peak
	.4byte gMetatileAttributes_stratus_peak
	.4byte NULL

	.align 2
gTileset_rankor_cave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_rankor_cave
	.4byte gTilesetPalettes_rankor_cave
	.4byte gMetatiles_rankor_cave
	.4byte gMetatileAttributes_rankor_cave
	.4byte NULL

	.align 2
gTileset_glazed_contest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glazed_contest
	.4byte gTilesetPalettes_glazed_contest
	.4byte gMetatiles_glazed_contest
	.4byte gMetatileAttributes_glazed_contest
	.4byte NULL

	.align 2
gTileset_cainwood::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_cainwood
	.4byte gTilesetPalettes_cainwood
	.4byte gMetatiles_cainwood
	.4byte gMetatileAttributes_cainwood
	.4byte NULL

	.align 2
gTileset_town1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_town1
	.4byte gTilesetPalettes_town1
	.4byte gMetatiles_town1
	.4byte gMetatileAttributes_town1
	.4byte NULL

	.align 2
gTileset_glazed_lab::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glazed_lab
	.4byte gTilesetPalettes_glazed_lab
	.4byte gMetatiles_glazed_lab
	.4byte gMetatileAttributes_glazed_lab
	.4byte NULL

	.align 2
gTileset_seafloor::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_seafloor
	.4byte gTilesetPalettes_seafloor
	.4byte gMetatiles_seafloor
	.4byte gMetatileAttributes_seafloor
	.4byte NULL

	.align 2
gTileset_reefen::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_reefen
	.4byte gTilesetPalettes_reefen
	.4byte gMetatiles_reefen
	.4byte gMetatileAttributes_reefen
	.4byte NULL

	.align 2
gTileset_town2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_town2
	.4byte gTilesetPalettes_town2
	.4byte gMetatiles_town2
	.4byte gMetatileAttributes_town2
	.4byte NULL

	.align 2
gTileset_kolo::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_kolo
	.4byte gTilesetPalettes_kolo
	.4byte gMetatiles_kolo
	.4byte gMetatileAttributes_kolo
	.4byte NULL

	.align 2
gTileset_alpha::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_alpha
	.4byte gTilesetPalettes_alpha
	.4byte gMetatiles_alpha
	.4byte gMetatileAttributes_alpha
	.4byte NULL

	.align 2
gTileset_reign::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_reign
	.4byte gTilesetPalettes_reign
	.4byte gMetatiles_reign
	.4byte gMetatileAttributes_reign
	.4byte NULL

	.align 2
gTileset_league_building::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_league_building
	.4byte gTilesetPalettes_league_building
	.4byte gMetatiles_league_building
	.4byte gMetatileAttributes_league_building
	.4byte NULL

	.align 2
gTileset_trainer_isle::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_trainer_isle
	.4byte gTilesetPalettes_trainer_isle
	.4byte gMetatiles_trainer_isle
	.4byte gMetatileAttributes_trainer_isle
	.4byte NULL

	.align 2
gTileset_ruins_of_alph::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_ruins_of_alph
	.4byte gTilesetPalettes_ruins_of_alph
	.4byte gMetatiles_ruins_of_alph
	.4byte gMetatileAttributes_ruins_of_alph
	.4byte NULL

	.align 2
gTileset_glazed_dock::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glazed_dock
	.4byte gTilesetPalettes_glazed_dock
	.4byte gMetatiles_glazed_dock
	.4byte gMetatileAttributes_glazed_dock
	.4byte NULL

	.align 2
gTileset_undersea_grotto::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_undersea_grotto
	.4byte gTilesetPalettes_undersea_grotto
	.4byte gMetatiles_undersea_grotto
	.4byte gMetatileAttributes_undersea_grotto
	.4byte NULL

	.align 2
gTileset_glenwood2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_glenwood2
	.4byte gTilesetPalettes_glenwood2
	.4byte gMetatiles_glenwood2
	.4byte gMetatileAttributes_glenwood2
	.4byte NULL
